---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: kubevault
  target:
    name: cloudflare-credentials
  data:
    - secretKey: api-token # trunk-ignore(checkov/CKV_SECRET_6)
      remoteRef:
        key: cloud-cloudflare
        property: api-token
