---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: kubevault
  namespace: default
spec:
  provider:
    kubernetes:
      remoteNamespace: kubevault-kvstore
      server:
        url: kubernetes.default
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          namespace: default
          key: ca.crt
      auth:
        serviceAccount:
          name: kubernetes.nr.chezmoi.sh
          namespace: kubevault-kvstore
