---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: default-gateway
spec:
  gatewayClassName: traefik-gateway
  listeners:
    - name: web
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: All
    - name: nx.chezmoi.sh-websecure
      hostname: '*.nx.chezmoi.sh'
      protocol: HTTPS
      port: 443
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: wildcard.nx.chezmoi.sh-certificate
      allowedRoutes:
        namespaces:
          from: All
    - name: chezmoi.sh-websecure
      hostname: '*.chezmoi.sh'
      protocol: HTTPS
      port: 443
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: wildcard.nx.chezmoi.sh-certificate
      allowedRoutes:
        namespaces:
          from: All
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard.nx.chezmoi.sh
spec:
  secretName: wildcard.nx.chezmoi.sh-certificate

  dnsNames:
    - '*.nx.chezmoi.sh'
    - '*.chezmoi.sh'
  duration: 2160h # 90d
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  renewBefore: 360h # 15d
