---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system

resources:
  # FluxCD controllers (only to manage HelmReleases as-code)
  - ../../base/fluxcd

  # Cert-manager for valid certificates
  - ../../base/cert-manager
  - cm-issuer-letsencrypt.yaml

  # ExternalDNS for managing DNS records
  - ../../base/external-dns
  - edo-secrets.yaml

  # ExternalSecrets for managing secrets
  - ../../base/external-secrets
  - eso-css-kubevault.yaml

  # Traefik for ingress routing
  - ../../base/gateway-api
  - ../../base/traefik
  - gateway-default.yaml

patches:
  # Configure ExternalDNS to work with Cloudflare
  - patch: |-
        apiVersion: helm.toolkit.fluxcd.io/v2
        kind: HelmRelease
        metadata:
          name: external-dns
        spec:
          values:
            provider:
              name: cloudflare
            env:
              - name: CF_API_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: cloudflare-credentials
                    key: api-token
            extraArgs:
              - --regex-domain-exclusion=.+\\.nr\\.chezmoi\\.sh
