---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authelia
spec:
  data:
    # Encryption keys
    - secretKey: session.encryption.key
      remoteRef:
        key: security-sso-authelia
        property: session_encryption_key
    - secretKey: storage.encryption.key
      remoteRef:
        key: security-sso-authelia
        property: storage_encryption_key
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: kubevault
  target:
    name: authelia
