---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authelia-oidc-legacy
spec:
  data:
    # Global OIDC secrets
    - secretKey: identity.providers.oidc.hmac.secret
      remoteRef:
        key: security-sso-authelia
        property: identity_providers_oidc_hmac_secret

    # ArgoCD OIDC client
    - secretKey: oidc.client.argocd
      remoteRef:
        key: security-sso-oidc-clients-argocd
        property: oidc_configuration

    # ArgoCD CLI OIDC client
    - secretKey: oidc.client.argocd_cli
      remoteRef:
        key: security-sso-oidc-clients-argocd-cli
        property: oidc_configuration

    # Budibase OIDC client
    - secretKey: oidc.client.budibase
      remoteRef:
        key: security-sso-oidc-clients-budibase
        property: oidc_configuration

    # Linkding OIDC client
    - secretKey: oidc.client.linkding
      remoteRef:
        key: security-sso-oidc-clients-linkding
        property: oidc_configuration

    # Mealie OIDC client
    - secretKey: oidc.client.mealie
      remoteRef:
        key: security-sso-oidc-clients-mealie
        property: oidc_configuration

    # Paperless-NGX OIDC client
    - secretKey: oidc.client.paperless_ngx
      remoteRef:
        key: security-sso-oidc-clients-paperless-ngx
        property: oidc_configuration

    # Proxmox OIDC client
    - secretKey: oidc.client.proxmox
      remoteRef:
        key: security-sso-oidc-clients-proxmox
        property: oidc_configuration
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: kubevault
  target:
    name: authelia-oidc
    creationPolicy: Merge
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authelia-oidc
spec:
  data:
    # OpenBao OIDC client
    - secretKey: oidc.client.openbao
      remoteRef:
        key: amiya.akn/openbao/auth/oidc-client
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault.chezmoi.sh
  target:
    name: authelia-oidc
    creationPolicy: Merge
    template:
      engineVersion: v2
      templateFrom:
      - target: Data
        # NOTE: this template is required to remove any key that are not handled by Authelia
        literal: |
          {{- range $client, $config := . }}
          {{- $client }}: |- {{ pick ($config | fromJson) "access_token_encrypted_response_alg" "access_token_encrypted_response_enc" "access_token_signed_response_alg" "audience" "authorization_encrypted_response_alg" "authorization_encrypted_response_enc" "authorization_signed_response_alg" "authorization_policy" "claims_policy" "client_id" "client_name" "client_secret" "consent_mode" "grant_types" "id_token_encrypted_response_alg" "id_token_encrypted_response_enc" "id_token_signed_response_alg" "introspection_encrypted_response_alg" "introspection_encrypted_response_enc" "introspection_signed_response_alg" "introspection_endpoint_auth_method" "introspection_endpoint_auth_signing_alg" "jwks" "jwks_uri" "key_id" "use" "algorithm" "key" "certificate_chain" "pkce_challenge_method" "pre_configured_consent_duration" "public" "pushed_authorization_request_endpoint_auth_method" "pushed_authorization_request_endpoint_auth_signing_alg" "redirect_uris" "request_object_encryption_alg" "request_object_encryption_enc" "request_object_signing_alg" "request_uris" "requested_audience_mode" "response_modes" "response_types" "revocation_endpoint_auth_method" "revocation_endpoint_auth_signing_alg" "require_pkce" "require_pushed_authorization_requests" "scopes" "sector_identifier_uri" "token_endpoint_auth_method" "token_endpoint_auth_signing_alg" "lifespan" | toYaml | nindent 2 }}
          {{- end }}
