---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: external-secrets
namespace: external-secrets-system
resources:
  - namespace.yaml
  - external-secrets.yaml
  - secret-store.yaml
