{{- if gt .Values.spec.autoscaling.minReplicas .Values.spec.autoscaling.maxReplicas -}}
{{- fail "spec.autoscaling.minReplicas cannot be greater than spec.autoscaling.maxReplicas" -}}
{{- end -}}
{{- if lt .Values.spec.autoscaling.minReplicas .Values.spec.autoscaling.maxReplicas -}}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  annotations: {{ include "release.annotations" . | default "{}" | nindent 4 }}
  labels: {{ include "release.labels" . | nindent 4 }}
  name: {{ include "release.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "release.name" . }}

  maxReplicas: {{ .Values.spec.autoscaling.maxReplicas }}
  minReplicas: {{ .Values.spec.autoscaling.minReplicas }}
  {{- with .Values.spec.autoscaling.behavior }}
  behavior: {{ toYaml . | nindent 4 }}
  {{- end -}}
  {{- with .Values.spec.autoscaling.metrics }}
  metrics: {{ toYaml . | nindent 4 }}
  {{- end -}}
{{- end -}}