{{- if or (hasKey (.Values.spec.distruptionBudget | default dict) "maxUnavailable") (hasKey (.Values.spec.distruptionBudget | default dict) "minAvailable") -}}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  annotations: {{ include "release.annotations" . | default "{}" | nindent 4 }}
  labels: {{ include "release.labels" . | nindent 4 }}
  name: {{ include "release.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels: {{ include "release.labels.selector" . | nindent 6 }}

  {{- with .Values.spec.distruptionBudget.maxUnavailable }}
  maxUnavailable: {{ . }}
  {{- end }}
  {{- with .Values.spec.distruptionBudget.minAvailable }}
  minAvailable: {{ . }}
  {{- end }}
  {{- with .Values.spec.distruptionBudget.unhealthyPodEvictionPolicy }}
  unhealthyPodEvictionPolicy: {{ . }}
  {{- end }}
{{- end -}}