---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nr-vpn

resources:
  - namespace.yaml

  - ../../base/tailscale
  - tailscale-secrets.yaml
  - tailscale-subnet-connector.yaml
