---
apiVersion: tailscale.com/v1alpha1
kind: Connector
metadata:
  name: homelab-subnet
spec:
  hostname: homelab-subnet-connector
  subnetRouter:
    advertiseRoutes:
      - 10.0.0.20/32
      - 10.0.0.89/32
      - 10.0.3.240/32
