---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system

resources:
  # This plugin is required to manage tun devices on the cluster nodes
  - ../../../../../../../catalog/kustomize/tailscale/plugins/tun-device-plugin
