---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: external-secrets
spec:
  interval: 44640m # 1 month
  url: https://charts.external-secrets.io/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
spec:
  interval: 44640m # 1 month
  timeout: 5m
  chart:
    spec:
      chart: external-secrets
      version: 0.10.0
      sourceRef:
        kind: HelmRepository
        name: external-secrets
      interval: 44640m # 1 month
  releaseName: external-secrets
  driftDetection:
    mode: enabled
