---
# This Helm values file contains all default values used by the ExternalSecrets
# Operator Helm chart.

# Disable the cert-controller and webhook because external-secret is not using webhooks
certController:
  create: false
webhook:
  create: false

# Enforce the security context for the operator
podSecurityContext:
  runAsUser: 23987
  runAsGroup: 23987
  runAsNonRoot: true
  fsGroup: 23987
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault
