---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

labels:
  - pairs:
      app.kubernetes.io/part-of: external-secrets-operator
      app.kubernetes.io/managed-by: kustomize
    includeSelectors: false
    includeTemplates: true

helmCharts:
  - name: external-secrets
    repo: https://charts.external-secrets.io/
    releaseName: external-secrets-operator
    namespace: external-secrets-system
    version: 0.14.4
    valuesFile: external-secrets-operator.helm-values.yaml
