---
# This Helm values file contains all hardened values used by the Cert-Manager
# Helm chart.

# Enforce the security context for the operator
securityContext:
  fsGroup: 34983
  runAsGroup: 34983
  runAsNonRoot: true
  runAsUser: 34983
  seccompProfile:
    type: RuntimeDefault
containerSecurityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
