[env]
KREW_ROOT = "{{ config_root }}/.mise/krew"
HELM_CACHE_HOME = "{{ config_root }}/.mise/helm/cache"
HELM_CONFIG_HOME = "{{ config_root }}/.mise/helm/config"
HELM_DATA_HOME = "{{ config_root }}/.mise/helm/data"
TALOSCONFIG = "{{ config_root }}/.mise/talos/config"
SOPS_AGE_KEY_FILE = "{{ config_root }}/.mise/age/key.txt"
KUBECONFIG = "{{ config_root }}/.mise/kubeconfig"
_.path = ["{{ config_root }}/scripts"]

[tools]
"aqua:terrastruct/d2" = "latest"
argocd = "latest"
helm = "latest"
krew = "latest"
kubectl = "latest"
talosctl = "latest"
"ubi:runmedev/runme" = "latest"
"go:github.com/oklog/ulid/v2/cmd/ulid" = "latest"
gum = "latest"
ksops = "latest"
dive = "latest"
ansible = "8.7"
yq = "latest"
