---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-authelia-to-aws-ses
  annotations:
    networkpolicy.kubernetes.io/description: >-
      Allow egress traffic from Authelia pods to AWS SES (ports 25, 465 and 587).
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: authelia
      app.kubernetes.io/name: authelia
  policyTypes:
    - Egress
  egress:
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
            except:
              - 10.0.0.0/8
              - 172.16.0.0/12
              - 192.168.0.0/16
      ports:
        - port: 25
          protocol: TCP
        - port: 465
          protocol: TCP
        - port: 587
          protocol: TCP
