# To adhere to security best practices, most clusters are configured with Admission
# Controllers in "restricted" mode.
# However, the Tailscale Operator requires modifying the pods' Security Context.
# Thus, it is essential to create a ProxyClass with the appropriate configurations to
# allow the operator to manage these Security Contexts.
---
apiVersion: tailscale.com/v1alpha1
kind: ProxyClass
metadata:
  name: restricted
spec:
  statefulSet:
    pod:
      tailscaleContainer:
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
            squat.ai/tun: "1"
          limits:
            memory: 128Mi
            squat.ai/tun: "1"
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false # NOTE: required for the Tailscale container to create sockets
          capabilities:
            drop:
              - ALL
          seccompProfile:
            type: RuntimeDefault
      securityContext:
        fsGroup: 25778
        runAsNonRoot: true
        runAsGroup: 25778
        runAsUser: 25778
