---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-issuer-account-key
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: letsencrypt-issuer-credentials
              key: api-token
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: letsencrypt-issuer-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: kubevault
  target:
    name: letsencrypt-issuer-credentials
  data:
    - secretKey: api-token # trunk-ignore(checkov/CKV_SECRET_6)
      remoteRef:
        key: cloud-cloudflare-nx.chezmoi.sh-cert-manager
        property: attribute.value
    - secretKey: email
      remoteRef:
        key: cloud-letsencrypt
        property: email
