---
apiVersion: v1
kind: Namespace
metadata:
  name: apps-catalog
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kubernetes-apps
  namespace: flux-system
spec:
  interval: 12h0m0s
  timeout: 5m0s
  retryInterval: 1m0s

  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./projects/maison/src/apps

  prune: true
  targetNamespace: apps-catalog
  wait: true
