---
# NOTE: because of the way the kustomize `labels` work, we need to include
#       all network policies in another kustomization file in order to
#       not apply labels selectors to them.
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: security-policies
  namespace: paperless-ngx
spec:
  interval: 2h0m0s
  timeout: 30s # if the apply of the resources takes more than 5 minutes, it will be considered as failed ...
  retryInterval: 30s # ... and will be retried every 30 seconds

  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./projects/maison/src/apps/paperless-ngx/policies

  commonMetadata:
    labels:
      app.kubernetes.io/managed-by: fluxcd
      app.kubernetes.io/name: paperless-ngx
      app.kubernetes.io/part-of: document-management-system

  prune: true
  wait: true
