---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  labels:
    app.kubernetes.io/component: database
    app.kubernetes.io/instance: paperless-ngx-database
  name: paperless-ngx-database
  namespace: paperless-ngx
spec:
  backup:
    barmanObjectStore: &barmanObjectStore
      data:
        compression: bzip2
      destinationPath: s3://cnpg-backups/maison.chezmoi.sh/paperless-ngx
      endpointURL: https://s3.chezmoi.sh:9000
      serverName: 01JJF4J1H0RVF9VPTYSTJQQTS1 # DRP::dst_ulid
      s3Credentials:
        accessKeyId:
          name: cnpg-s3-credentials
          key: access_key_id
        secretAccessKey:
          name: cnpg-s3-credentials
          key: access_secret_key
      wal:
        compression: bzip2
    retentionPolicy: 30d
  bootstrap:
    # initdb:
    #   database: app
    #   owner: app
    recovery:
      source: recoveryBackup
  description: PostgreSQL database dedicated to Paperless-NGX
  externalClusters:
    - name: recoveryBackup
      barmanObjectStore:
        <<: *barmanObjectStore
        serverName: 01JHBM7C42DXESVSHDSSHNC6KQ # DRP::src_ulid
  instances: 1
  storage:
    size: 5Gi
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  labels:
    app.kubernetes.io/component: database-backup
  name: paperless-ngx-database
  namespace: paperless-ngx
spec:
  schedule: "@daily"
  backupOwnerReference: cluster
  cluster:
    name: paperless-ngx-database
