---
# trunk-ignore-all(checkov/CKV_K8S_21): Namespace is managed by kustomize
# trunk-ignore-all(checkov/CKV2_K8S_6): NetworkPolicy will be defined whith Authelia
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: authelia-sso
    app.kubernetes.io/name: authelia
    app.kubernetes.io/part-of: sso
    app.kubernetes.io/version: 4.38.11
  name: authelia
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: authelia-sso
      app.kubernetes.io/name: authelia
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: authelia-sso
        app.kubernetes.io/name: authelia
    spec:
      automountServiceAccountToken: false
      containers:
        - env:
            - name: X_AUTHELIA_CONFIG_FILTERS
              value: template
          image: docker.io/authelia/authelia:4.38.11@sha256:b4d09f0850f46830795d7f1f49c1afad6849cad8a589a10931d3ef45a0fb1e6b
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /api/health
              port: http
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 30
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          name: authelia
          ports:
            - containerPort: 9091
              name: http
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /api/health
              port: http
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 5
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          resources:
            limits:
              cpu: 200m
              memory: 128Mi
            requests:
              cpu: 10m
              memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 19937
            runAsGroup: 36550
            seccompProfile:
              type: RuntimeDefault
          startupProbe:
            httpGet:
              path: /api/health
              port: http
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 2
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 15
          volumeMounts:
            - mountPath: /config
              name: authelia-configuration
            - mountPath: /var/lib/authelia
              name: authelia-data
            - mountPath: /var/run/secrets/authelia.com
              name: authelia-secrets
              readOnly: true
      enableServiceLinks: false
      securityContext:
        fsGroup: 36550
        runAsUser: 19937
        runAsNonRoot: true
        runAsGroup: 36550
      volumes:
        - name: authelia-configuration
          configMap:
            name: authelia-configuration
        - name: authelia-data
          persistentVolumeClaim:
            claimName: authelia-data
        - name: authelia-secrets
          projected:
            sources:
              - secret:
                  name: authelia-secrets
              - secret:
                  name: authelia-oidc-linkding
              - secret:
                  name: authelia-oidc-proxmox
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/instance: authelia-sso
    app.kubernetes.io/name: authelia
    app.kubernetes.io/part-of: sso
    app.kubernetes.io/version: 4.38.11
  name: authelia-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: authelia-sso
    app.kubernetes.io/name: authelia
    app.kubernetes.io/part-of: sso
    app.kubernetes.io/version: 4.38.11
  name: authelia-configuration
# NOTE: The configuration is generated by Kustomize
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authelia-credentials
spec:
  refreshInterval: 15s
  secretStoreRef:
    kind: ClusterSecretStore
    name: kubevault
  target:
    name: authelia-secrets
  dataFrom:
    - extract:
        key: security-sso-authelia
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authelia-oidc-linkding
spec:
  refreshInterval: 15s
  secretStoreRef:
    kind: ClusterSecretStore
    name: kubevault
  target:
    name: authelia-oidc-linkding
  data:
    - secretKey: oidc_client_linkding
      remoteRef:
        key: security-sso-oidc-clients-linkding
        property: oidc_configuration
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authelia-oidc-proxmox
spec:
  refreshInterval: 15s
  secretStoreRef:
    kind: ClusterSecretStore
    name: kubevault
  target:
    name: authelia-oidc-proxmox
  data:
    - secretKey: oidc_client_proxmox
      remoteRef:
        key: security-sso-oidc-clients-proxmox
        property: oidc_configuration
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: authelia-sso
    app.kubernetes.io/name: authelia
    app.kubernetes.io/part-of: sso
    app.kubernetes.io/version: 4.38.11
  name: authelia
spec:
  ports:
    - appProtocol: http
      name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app.kubernetes.io/instance: authelia-sso
    app.kubernetes.io/name: authelia
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  labels:
    app.kubernetes.io/instance: authelia-sso
    app.kubernetes.io/name: authelia
    app.kubernetes.io/part-of: sso
    app.kubernetes.io/version: 4.38.11
  name: authelia
spec:
  parentRefs:
    - kind: Gateway
      name: default-gateway
      namespace: traefik-system
      sectionName: nr.chezmoi.sh-websecure
  hostnames:
    - sso.nr.chezmoi.sh
  rules:
    - backendRefs:
        - kind: Service
          name: authelia
          port: 80
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    app.kubernetes.io/instance: authelia-sso
    app.kubernetes.io/name: authelia
    app.kubernetes.io/part-of: sso
    app.kubernetes.io/version: 4.38.11
  name: authelia
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: authelia-sso
      app.kubernetes.io/name: authelia
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: traefik-system
          podSelector:
            matchLabels:
              app.kubernetes.io/instance: traefik-traefik-system
              app.kubernetes.io/name: traefik
      ports:
        - port: 9091
  egress:
    - to:
        - namespaceSelector: {}
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - port: 53
          protocol: UDP
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - port: 25
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/instance: yaldap-sso
              app.kubernetes.io/name: yaldap
      ports:
        - port: 8389
