# ┌─────────────────────────────────────────────────────────────────────────────┐
# │                           Service Catalog Entry                             │
# ├─────────────────────────────────────────────────────────────────────────────┤
# │ name: cloudnative-pg                                                        │
# │ description: |                                                              │
# │   CloudNativePG is a comprehensive platform designed to seemlessly          │
# │   manage PostgreSQL databases within Kubernetes environments.               │
# │ tags:                                                                       │
# │   - database                                                                │
# │   - postgresql                                                              │
# │ links:                                                                      │
# │   - title: CloudNativePG Website                                            │
# │     url: https://cloudnative-pg.io/                                         │
# │   - title: CloudNativePG Documentation                                      │
# │     url: https://cloudnative-pg.io/documentation/1.25/                      │
# │   - title: CloudNativePG Helm Chart                                         │
# │     url: https://artifacthub.io/packages/helm/cloudnative-pg/cloudnative-pg │
# └─────────────────────────────────────────────────────────────────────────────┘
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cloudnative-pg
  namespace: cnpg-system
spec:
  interval: 24h0m0s # NOTE: don't need to check for updates often
  url: https://cloudnative-pg.io/charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudnative-pg
  namespace: cnpg-system
spec:
  interval: 12h0m0s
  chart:
    spec:
      chart: cloudnative-pg
      version: 0.23.0
      sourceRef:
        kind: HelmRepository
        name: cloudnative-pg
        namespace: cnpg-system

  # Customisation of the HelmRelease behaviour
  driftDetection: { mode: warn }
  test: { enable: true }
  rollback: { cleanupOnFail: true, recreate: true }

  releaseName: cloudnative-pg
