---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations: {{ include "release.annotations" . | default "{}" | nindent 4 }}
  labels: {{ include "release.labels" . | nindent 4 }}
  name: {{ include "release.name" . }}
  namespace: {{ .Release.Namespace }}