---
# This ApplicationSet deploys all resources like ClusterSecretStore, ClusterIssuer, etc.
# in order to be used by other applications.
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-configuration
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - clusters: {}
  template:
    metadata:
      name: "{{ .name }}-configuration"
    spec:
      sources:
        - repoURL: https://github.com/chezmoi-sh/atlas.git
          path: projects/{{ index .metadata.annotations "argocd.argoproj.io/slug-name" | default .name }}/src/infrastructure/kubernetes/default
          targetRevision: main
      destination:
        server: "{{ .server }}"
        namespace: external-secrets-system
