---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd-system

resources:
  - cluster-configuration.applicationset.yaml
  - ../../../../../../catalog/argocd/cert-manager
  - ../../../../../../catalog/argocd/external-secrets-operator

patches:
  # Override the default values in the ApplicationSet
  - patch: |-
      - op: add
        path: /spec/template/spec/sources/1/helm/valueFiles/-
        value: $origin/project/{{ .name }}/src/infrastructure/kubernetes/cert-manager/override.helmvalues.yaml
      - op: add
        path: /spec/template/spec/sources/1/helm/valueFiles/-
        value: $origin/project/{{ index .metadata.annotations "argocd.argoproj.io/slug-name" | default .name }}/src/infrastructure/kubernetes/cert-manager/override.helmvalues.yaml
    target:
      kind: ApplicationSet
      name: cert-manager
  - patch: |-
      - op: add
        path: /spec/template/spec/sources/1/helm/valueFiles/-
        value: $origin/project/{{ .name }}/src/infrastructure/kubernetes/external-secrets-system/override.helmvalues.yaml
      - op: add
        path: /spec/template/spec/sources/1/helm/valueFiles/-
        value: $origin/project/{{ index .metadata.annotations "argocd.argoproj.io/slug-name" | default .name }}/src/infrastructure/kubernetes/external-secrets-system/override.helmvalues.yaml
    target:
      kind: ApplicationSet
      name: external-secrets-operator

  # Override all ApplicationSets to configure default values
  - patch: |-
      # Configure the default project name (infrastructure)
      - op: replace
        path: /spec/template/spec/project
        value: infrastructure

      # Configure all application to automatically sync
      - op: replace
        path: /spec/template/spec/syncPolicy
        value:
          automated:
            prune: false
            selfHeal: true
          syncOptions:
            - ApplyOutOfSyncOnly=true
            - CreateNamespace=true
            - Delete=confirm
            - Prune=confirm
            - ServerSideApply=true
    target:
      kind: ApplicationSet
