---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: cert-manager
namespace: cert-manager-system
resources:
  - namespace.yaml
  - cert-manager.yaml
  - letsencrypt-issuer.yaml
