---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cert-manager
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - clusters:
        selector:
          matchExpressions:
            - key: cert-manager.appset.chezmoi.sh/enable
              operator: NotIn
              values: ["false"]
  template:
    metadata:
      name: "{{ .name }}-cert-manager"
    spec:
      sources:
        - repoURL: https://github.com/chezmoi-sh/atlas.git
          targetRevision: main
          ref: origin
        - chart: cert-manager
          repoURL: https://charts.jetstack.io
          targetRevision: 1.17.1
          helm:
            releaseName: cert-manager
            valueFiles:
              # default configuration with all required values
              - $origin/catalog/argocd/cert-manager/helmvalues/default.helmvalues.yaml
              # enhanced configuration to enforce security best practices
              - $origin/catalog/argocd/cert-manager/helmvalues/hardened.helmvalues.yaml
            ignoreMissingValueFiles: true
      destination:
        server: "{{ .server }}"
        namespace: cert-manager-system

      # NOTE: by default, this ApplicationSet is configured to NOT BE UPDATED
      #       automatically. This is to prevent unwanted changes to the cluster.
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
