---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # - source-controller v1.3.0
  - https://github.com/fluxcd/source-controller.git//config/crd/?ref=v1.3.0
  - https://github.com/fluxcd/source-controller.git//config/rbac/?ref=v1.3.0
  - https://github.com/fluxcd/source-controller.git//config/manager/?ref=v1.3.0

  # - helm-controller v1.0.1
  - https://github.com/fluxcd/helm-controller.git//config/crd/?ref=v1.0.1
  - https://github.com/fluxcd/helm-controller.git//config/rbac/?ref=v1.0.1
  - https://github.com/fluxcd/helm-controller.git//config/manager/?ref=v1.0.1
