---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: budibase
spec:
  interval: 12h0m0s
  timeout: 30s
  retryInterval: 0s

  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./projects/maison/src/apps/budibase

  prune: true
  wait: true
