---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # NOTE: Applications are manually installed using this kustomization to avoid
  #       installing automatically if it is not needed.
  - actual-budget.yaml
  - budibase.yaml
  - jellyfin.yaml
  - jellyseerr.yaml
  - linkding.yaml
  - mealie.yaml
  - n8n.yaml
  - paperless-ngx.yaml
