---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: paperless-ngx
spec:
  interval: 12h0m0s
  timeout: 30s # if the apply of the resources takes more than 5 minutes, it will be considered as failed ...
  retryInterval: 30s # ... and will be retried every 30 seconds

  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./projects/maison/src/apps/paperless-ngx

  prune: true
  wait: true
