---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: external-dns
spec:
  interval: 44640m # 1 month
  url: https://kubernetes-sigs.github.io/external-dns/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
spec:
  interval: 44640m # 1 month
  timeout: 5m
  chart:
    spec:
      chart: external-dns
      version: 1.14.5
      sourceRef:
        kind: HelmRepository
        name: external-dns
      interval: 44640m # 1 month
  releaseName: external-dns
  driftDetection:
    mode: enabled
  values:
    logLevel: debug
    sources:
      - gateway-grpcroute
      - gateway-httproute
      - gateway-tcproute
      - gateway-tlsroute
      - gateway-udproute
      - ingress
      - service
      # - traefik-proxy
