# The LDAPS Gateway provides secure LDAP over TLS access to the YALDAP service.
# This configuration enables LDAPS (LDAP over TLS) on port 636 with proper
# certificate management for secure authentication.
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ldaps.chezmoi.sh
  namespace: traefik-system
spec:
  secretName: ldaps.chezmoi.sh-certificate
  dnsNames:
    - ldaps.chezmoi.sh
  duration: 2160h # 90d
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  renewBefore: 360h # 15d
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: ldaps-gateway
spec:
  gatewayClassName: traefik-gateway
  listeners:
    - name: ldaps
      hostname: ldaps.chezmoi.sh
      protocol: TLS
      port: 636
      tls:
        mode: Terminate
        certificateRefs:
          - group: ""
            kind: Secret
            name: ldaps.chezmoi.sh-certificate
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              kubernetes.io/metadata.name: sso
