---
# This cluster secret store is used to access the secrets dedicated to a
# specific project, following the ADR-002: Secrets Mount Topology.
#
# NOTE: All ${} variables are replaced by the values from the project
#       configuration by ArgoCD.
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault.chezmoi.sh
spec:
  provider:
    vault:
      server: https://vault.chezmoi.sh
      version: v2
      auth:
        kubernetes:
          # mountPath: {{ .Values.clusterName }}
          # role: {{ .Values.clusterName }}-eso-role
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets-system
