---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubevault
spec:
  destination:
    namespace: kubevault-kvstore
    server: https://kubernetes.default.svc
  project: system
  sources:
    - repoURL: https://github.com/chezmoi-sh/vault.kubernetes.git
      targetRevision: main
      path: .
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Delete=confirm
      - Prune=confirm
      - ServerSideApply=true
