---
# trunk-ignore-all(checkov/CKV_K8S_21): namespace is set in the transformer
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    argocd.argoproj.io/description: |
      ServiceAccount used by OpenBao for Kubernetes auth method token review.
      This SA is granted the system:auth-delegator ClusterRole to validate
      service account tokens presented to OpenBao for authentication.
  name: openbao-token-reviewer
