---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: longhorn-system

resources:
  - default.recurringjobs.yaml
  - longhorn.externalsecret.yaml
  - longhorn.httproute.yaml
  - namespace.yaml

helmCharts:
  - name: longhorn
    repo: https://charts.longhorn.io/
    version: 1.8.1
    valuesFile: longhorn.helmvalues/default.yaml
