---
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xclustervaults.vault.chezmoi.sh
spec:
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                  description: >
                    The name of the Kubernetes cluster to integrate with OpenBao.
                  example: "amiya.akn"
                host:
                  type: string
                  description: >
                    The address of the Kubernetes cluster (API server endpoint).
                  example: "https://kubernetes.amiya.akn:6443"
                caCert:
                  type: object
                  description: >
                    CA certificate configuration for cluster authentication.
                  properties:
                    secretRef:
                      type: object
                      description: >
                        Reference to a secret containing the CA certificate.
                      properties:
                        certName:
                          type: string
                          description: >
                            Name of the labels `vault.crossplane.chezmoi.sh/ca-cert-name` on the secret containing the CA certificate.
                        key:
                          type: string
                          description: >
                            Key in the secret containing the CA certificate.
                          default: "ca.crt"
                      required:
                        - certName
                  required:
                    - secretRef
                providerConfigRef:
                  type: object
                  description: >
                    Reference to the ProviderConfig to use for OpenBao resources.
                  properties:
                    name:
                      type: string
                      description: >
                        Name of the ProviderConfig.
                      default: "default"
                additionalPolicies:
                  type: array
                  description: >
                    List of additional policies to create and add to ESO tokenPolicies.
                  items:
                    type: string
                  default: []
              required:
                - name
                - host
                - caCert
