---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # ClusterVault (vault running outside of the cluster)
  - external.x.openbao.yaml
  - external.xrd.yaml

  # LocalClusterVault (vault running inside the cluster)
  - local.x.openbao.yaml
  - local.xrd.yaml

patches:
  - path: external.xrd.v1alpha1.yaml
  - path: local.xrd.v1alpha1.yaml
