---
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xlocalclustervaults.vault.chezmoi.sh
spec:
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                  description: >
                    The name of the local Kubernetes cluster to integrate with OpenBao.
                  example: "local.akn"
                providerConfigRef:
                  type: object
                  description: >
                    Reference to the ProviderConfig to use for OpenBao resources.
                  properties:
                    name:
                      type: string
                      description: >
                        Name of the ProviderConfig.
                      default: "default"
                additionalPolicies:
                  type: array
                  description: >
                    List of additional policies to create and add to ESO tokenPolicies.
                  items:
                    type: string
                  default: []
              required:
                - name
