---
# Source: traefik/templates/rbac/clusterroles.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations: 
    custom.chezmoi.sh/everywhere: "true"
  labels: 
    app.kubernetes.io/name: traefik-fully-customized
    app.kubernetes.io/instance: fully-customized
    app.kubernetes.io/version: "v3.1.2"
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: traefik-0.1.0
    custom.chezmoi.sh/everywhere: "true"
  name: traefik:default-fully-customized:traefik
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["nodes", "services", "secrets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["discovery.k8s.io"]
    resources: ["endpointslices"]
    verbs: ["list", "watch"]
  - apiGroups: ["extensions", "networking.k8s.io"]
    resources: ["ingressclasses", "ingresses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["extensions", "networking.k8s.io"]
    resources: ["ingresses/status"]
    verbs: ["update"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["list", "watch"]
  - apiGroups: [gateway.networking.k8s.io]
    resources:
      - gatewayclasses
      - gateways
      - httproutes
      - referencegrants
      - tcproutes
      - tlsroutes
    verbs: [get, list, watch]
  - apiGroups: [gateway.networking.k8s.io]
    resources:
      - gatewayclasses/status
      - gateways/status
      - httproutes/status
      - tcproutes/status
      - tlsroutes/status
    verbs: [update]
---
# Source: traefik/templates/rbac/clusterroles.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations: 
    custom.chezmoi.sh/everywhere: "true"
  labels: 
    app.kubernetes.io/name: traefik-fully-customized
    app.kubernetes.io/instance: fully-customized
    app.kubernetes.io/version: "v3.1.2"
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: traefik-0.1.0
    custom.chezmoi.sh/everywhere: "true"
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
    rbac.authorization.k8s.io/aggregate-to-view: "true"
  name: traefik:default-fully-customized:traefik-crds
  namespace: default
rules:
  - apiGroups: [traefik.io]
    resources:
      - ingressroutes
      - ingressroutetcps
      - ingressrouteudps
      - middlewares
      - middlewaretcps
      - serverstransports
      - serverstransporttcps
      - tlsoptions
      - tlsstores
      - traefikservices
    verbs: [get, list, watch]
