---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: external-dns
spec:
  interval: 44640m # 1 month
  url: https://kubernetes-sigs.github.io/external-dns/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
spec:
  interval: 44640m # 1 month
  timeout: 5m
  chart:
    spec:
      chart: external-dns
      version: 1.14.5
      sourceRef:
        kind: HelmRepository
        name: external-dns
      interval: 44640m # 1 month
  releaseName: external-dns
  driftDetection:
    mode: enabled
  values:
    logLevel: debug
    sources:
      - gateway-grpcroute
      - gateway-httproute
      - gateway-tcproute
      - gateway-tlsroute
      - gateway-udproute
      - ingress
      - service
      # - traefik-proxy
    provider:
      name: cloudflare
    env:
      - name: CF_API_TOKEN
        valueFrom:
          secretKeyRef:
            name: cloudflare-credentials
            key: api-token
    extraArgs:
      - --regex-domain-exclusion=.+\\.nr\\.chezmoi\\.sh # Exclude all subdomains of nr.chezmoi.sh as they are already managed by IaC
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: kubevault
  target:
    name: cloudflare-credentials
  data:
    - secretKey: api-token # trunk-ignore(checkov/CKV_SECRET_6)
      remoteRef:
        key: cloud-cloudflare
        property: api-token
