---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cert-manager
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - clusters:
        selector:
          matchExpressions:
            - key: cert-manager.appset.chezmoi.sh/enable
              operator: NotIn
              values: ["false"]
  template:
    metadata:
      name: "{{ .name }}-cert-manager"
    spec:
      source:
        path: |-
          {{- with index .metadata.annotations "cert-manager.appset.chezmoi.sh/kustomize-with" -}}
            {{ index .metadata.annotations "cert-manager.appset.chezmoi.sh/kustomize-with" }}
          {{- else -}}
            catalog/kustomize/cert-manager/
          {{- end -}}
        targetRevision: main
      destination:
        server: "{{ .server }}"
        namespace: cert-manager-system

      syncPolicy:
        automated:
          prune: true # Prune resources that are no more in the repository
          selfHeal: true # Self-heal resources that are no more in the desired state
