---
apiVersion: vault.vault.upbound.io/v1alpha1
kind: Policy
metadata:
  name: amiya.akn-crossplane-policy
spec:
  forProvider:
    name: amiya.akn-crossplane-policy
    policy: |
      # Allow Crossplane to manage all third-parties secrets on the shared mount
      path "shared/+/third-parties/*" {
        capabilities = ["create", "read", "update", "delete", "list"]
      }

  providerConfigRef:
    name: default
