---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - auth-backend.yaml
  - auth-backend-config.yaml
  - crossplane.role.yaml
  - crossplane.policy.yaml
  - eso.policy.yaml
  - eso.role.yaml
  - mount.yaml
