---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns-adguard
  namespace: external-dns-system
spec:
  interval: 12h0m0s
  chart:
    spec:
      chart: external-dns
      version: 1.15.0
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: external-dns-system

  # Customisation of the HelmRelease behaviour
  driftDetection: { mode: warn }
  test: { enable: true }
  rollback: { cleanupOnFail: true, recreate: true }

  releaseName: external-dns-adguard
  values:
    sources:
      # - gateway-grpcroute
      - gateway-httproute
      # - gateway-tcproute
      - gateway-tlsroute
      # - gateway-udproute
      - ingress
      - service
      # - traefik-proxy
    extraArgs:
      - --annotation-filter=external-dns.alpha.kubernetes.io/exclude-adguard notin (true) # NOTE: exclude resources with annotation

    policy: sync
    provider:
      name: webhook
      webhook:
        image:
          repository: ghcr.io/muhlba91/external-dns-provider-adguard
          tag: v8.0.0
        env:
          - name: LOG_LEVEL
            value: info
