---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-credentials
  namespace: external-dns-system
spec:
  refreshInterval: 1h
  target:
    name: cloudflare-credentials
  data:
    - secretKey: api-token # trunk-ignore(checkov/CKV_SECRET_6)
      remoteRef: { key: "", property: "" }
