---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: crossplane-system

resources:
  - functions.yaml
  - provider.aws.yaml
  - provider.cloudflare.yaml
  - runtimeconfigs.yaml

  # SecOps (Network Policies)

helmCharts:
  - name: crossplane
    repo: https://charts.crossplane.io/master/
    releaseName: crossplane
    version: 1.20.0-rc.0.45.gb0cc38c10
    valuesFile: crossplane.helmvalues/default.yaml
    additionalValuesFiles:
      - crossplane.helmvalues/hardened.yaml
