---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system

resources:
  # ExternalDNS for managing DNS records
  - ../../base/external-dns-cloudflare
  - ../../base/external-dns-adguard
  - edo-secrets.yaml

  # Traefik for ingress routing
  - ../../base/traefik
  - gateway-default.yaml

patches:
  # Configure ExternalDNS to work with Cloudflare
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --regex-domain-exclusion=.+\\.nr\\.chezmoi\\.sh
      - op: add
        path: "/spec/template/spec/containers/0/env"
        value:
          - name: CF_API_TOKEN
            valueFrom:
              secretKeyRef:
                name: cloudflare-credentials
                # trunk-ignore(checkov/CKV_SECRET_6)
                key: api-token
    target:
      kind: Deployment
      name: external-dns-cloudflare
      namespace: kube-system
