---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tailscale-operator-oauth
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: kubevault
  target:
    name: tailscale-operator-oauth
  data:
    - secretKey: client_id
      remoteRef:
        key: cloud-tailscale-nx
        property: operator-oauth-client-id
    - secretKey: client_secret
      remoteRef:
        key: cloud-tailscale-nx
        property: operator-oauth-client-secret
