---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: external-dns
    repo: https://kubernetes-sigs.github.io/external-dns/
    releaseName: external-dns-cloudflare
    namespace: kube-system
    version: 1.16.1
    valuesInline:
      logLevel: debug
      sources:
        # - gateway-grpcroute
        - gateway-httproute
        # - gateway-tcproute
        - gateway-tlsroute
        # - gateway-udproute
        - ingress
        - service
        # - traefik-proxy
      txtOwnerId: kubernetes.nx.chezmoi.sh
      provider:
        name: cloudflare
