---
apiVersion: account.cloudflare.crossplane.io/v1alpha1
kind: APIToken
metadata:
  name: nx-chezmoi-sh-external-dns
spec:
  forProvider:
    name: (nx.chezmoi.sh) - External DNS
    policy:
      - effect: allow
        permissionGroups:
          - c8fed203ed3043cba015a93ad1616f1f # Zone Read
          - 4755a26eedb94da69e1066d98aa820be # DNS Write
        resources:
          com.cloudflare.api.account.zone.2734d7b22cf00222046320ed3187cb94: "*"
    condition:
      - requestIp:
          - in: [176.145.158.72/32]
