# trunk-ignore-all(checkov/CKV_K8S_21): This file is overrided by Kustomize
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    tailscale.com/proxy-class: restricted
  name: sso
spec:
  defaultBackend:
    service:
      name: authelia
      port:
        number: 80
  ingressClassName: tailscale
  tls:
    - hosts:
        - sso
