---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: budibase
  namespace: budibase
spec:
  interval: 24h0m0s # NOTE: don't need to check for updates often
  url: https://budibase.github.io/budibase/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: budibase
  namespace: budibase
spec:
  interval: 12h0m0s
  chart:
    spec:
      chart: budibase
      version: 3.0.259
      sourceRef:
        kind: HelmRepository
        name: budibase
      interval: 24h0m0s

  # Customisation of the HelmRelease behaviour
  driftDetection: { mode: warn }
  test: { enable: false } # NOTE: bugged on this chart
  rollback: { cleanupOnFail: true, recreate: true }

  releaseName: budibase
