---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: crossplane
spec:
  interval: 44640m # 1 month
  url: https://charts.crossplane.io/master/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: crossplane
spec:
  interval: 44640m # 1 month
  timeout: 5m
  chart:
    spec:
      chart: crossplane
      version: 1.18.0-rc.0.61.ged4e659c
      sourceRef:
        kind: HelmRepository
        name: crossplane
      interval: 44640m # 1 month
  releaseName: crossplane
  driftDetection:
    mode: enabled
