---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - operator-oauth.externalsecret.yaml
  - restricted.proxyclass.yaml

transformers:
  - |-
    apiVersion: builtin
    kind: NamespaceTransformer
    metadata:
      name: tailscale-system
      namespace: tailscale-system
    unsetOnly: true
