# This manifest deploys a custom CoreDNS configuration and some
# additional service to allow CoreDNS to resolve Tailscale
# addresses using the Tailscale DNS server.
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  ts-net.server: |
    ts.net {
        errors
        cache 30
        forward . 10.43.0.100:53 {
            force_tcp
        }
    }
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    # tailscale.com/tags: tags:kubernetes-nameserver
    tailscale.com/hostname: nameserver-<cluster-name>
    tailscale.com/tailnet-ip: 100.100.100.100
  labels:
    tailscale.com/proxy-class: restricted-egress
  name: nameserver
spec:
  externalName: nameserver
  type: ExternalName
---
apiVersion: v1
kind: Service
metadata:
  name: nameserver-static
spec:
  clusterIP: 10.43.0.100
  ports:
    - name: dns
      port: 53
      protocol: UDP
      targetPort: 53
    - name: dns-tcp
      port: 53
      protocol: TCP
      targetPort: 53
  selector:
    tailscale.com/managed: "true"
    tailscale.com/parent-resource: nameserver
    tailscale.com/parent-resource-ns: tailscale-system
    tailscale.com/parent-resource-type: svc
  type: ClusterIP
