---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: operator-oauth
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: kubevault
  target:
    name: operator-oauth
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        # key: cloud-tailscale-{{ .Values.clusterName }}
        metadataPolicy: None
        property: operator-oauth-client-id
      secretKey: client_id
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        # key: cloud-tailscale-{{ .Values.clusterName }}
        metadataPolicy: None
        property: operator-oauth-client-secret
      secretKey: client_secret
