# Cloudflare datasource for chezmoi.sh (Zome and Account)
#
# Description:
#   These resources will add the chezmoi.sh zone and account to Cloudflare in
#   order to use them lately with other Cloudflare resources.
---
apiVersion: account.cloudflare.crossplane.io/v1alpha1
kind: Account
metadata:
  labels:
    cf.chezmoi.sh/account: main
  name: chezmoi-sh
spec:
  managementPolicies: [Observe]
  forProvider: {}
---
apiVersion: zone.cloudflare.crossplane.io/v1alpha1
kind: Zone
metadata:
  labels:
    cf.chezmoi.sh/zone: chezmoi.sh
  name: chezmoi-sh
spec:
  managementPolicies: [Observe]
  forProvider:
    accountIdSelector:
      matchLabels:
        cf.chezmoi.sh/account: main
