---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Required modules
  - ../../../../../catalog/crossplane/domainidentity.amazonses.chezmoi.sh

  # Provider configurations
  - provider.aws.config.yaml
  - provider.cloudflare.config.yaml

  # Cloudfare resources
  - cloudflare.zone.yaml

  # AWS resources
  - aws.domainidentity.yaml
