# Cloudflare Crossplane provider configuration
#
# Description:
#   This ProviderConfig configures the Cloudflare provider for Crossplane.
---
apiVersion: cloudflare.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-chezmoish
      name: cloudflare-credentials
      key: credentials
