---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: tailscale
spec:
  interval: 44640m # 1 month
  url: https://pkgs.tailscale.com/helmcharts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale-operator
spec:
  interval: 44640m # 1 month
  timeout: 5m
  chart:
    spec:
      chart: tailscale-operator
      version: 1.74.1
      sourceRef:
        kind: HelmRepository
        name: tailscale
      interval: 44640m # 1 month
  releaseName: tailscale-operator
  driftDetection:
    mode: enabled
  values:
    installCRDs: true
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tailscale-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: kubevault
  target:
    name: operator-oauth
  data:
    - secretKey: client_id
      remoteRef:
        key: cloud-tailscale
        property: operator-oauth-client-id
    - secretKey: client_secret
      remoteRef:
        key: cloud-tailscale
        property: operator-oauth-client-secret
---
apiVersion: tailscale.com/v1alpha1
kind: Connector
metadata:
  name: homelab-subnet
spec:
  hostname: homelab-subnet-connector
  subnetRouter:
    advertiseRoutes:
      - 10.0.0.20/32
      - 10.0.0.89/32
      - 10.0.3.240/32
