---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: tailscale
spec:
  interval: 44640m # 1 month
  url: https://pkgs.tailscale.com/helmcharts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale-operator
spec:
  interval: 44640m # 1 month
  timeout: 5m
  chart:
    spec:
      chart: tailscale-operator
      version: 1.74.1
      sourceRef:
        kind: HelmRepository
        name: tailscale
      interval: 44640m # 1 month
  releaseName: tailscale-operator
  driftDetection:
    mode: enabled
  values:
    installCRDs: true
