# trunk-ignore-all(checkov/CKV_SECRET_6): no secrets in this file
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: crossplane-hasschezmoish

resources:
  - namespace.yaml
  - cloudflare.dns.static-records.yaml
  - cloudflare.iam.home-assistant.yaml

patches:
  - patch: |-
      - op: add
        path: /spec/writeConnectionSecretToRef
        value:
          name: cloud-cloudflare-hass.chezmoi.sh-home-assistant
          namespace: kubevault-kvstore
    target:
      group: account.cloudflare.crossplane.io
      version: v1alpha1
      kind: APIToken
      name: hass-chezmoi-sh-home-assistant
