# AWS IAM Resources for n8n
#
# Description:
#   These resources create an AWS IAM User with the necessary permissions for n8n
#   to send emails using Amazon SES. The configuration includes:
#   - IAM Policy with SES permissions
#   - IAM User
#   - Policy attachment
#   - Access Key
#   - RBAC permissions for Kubernetes
#
# Permissions:
#   - SES:SendEmail: Allows sending emails through Amazon SES
#   - SES:SendRawEmail: Allows sending raw emails with custom headers
#
# Security:
#   - Access keys are stored in Kubernetes secrets in the kubevault-kvstore namespace
#   - RBAC rules restrict access to the secret to the n8n service account
#   - The IAM user is scoped to a specific path (/maison.chezmoi.sh/)
#
# Usage:
#   This configuration enables n8n to send emails through Amazon SES for
#   workflow automation and notifications.
---
apiVersion: iam.aws.upbound.io/v1beta1
kind: Policy
metadata:
  annotations:
    crossplane.io/external-name: N8NSESSender
  name: maison.chezmoi.sh-amazonses-n8n
  namespace: kubevault-kvstore
spec:
  forProvider:
    path: /maison.chezmoi.sh/
    policy: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Sid": "AllowSendingEmails",
            "Effect": "Allow",
            "Action": [
              "ses:SendEmail",
              "ses:SendRawEmail"
            ],
            "Resource": "arn:aws:ses:us-east-1:*:identity/*"
          }
        ]
      }
---
apiVersion: iam.aws.upbound.io/v1beta1
kind: User
metadata:
  annotations:
    crossplane.io/external-name: n8n
  name: maison.chezmoi.sh-amazonses-n8n
  namespace: kubevault-kvstore
spec:
  forProvider:
    path: /maison.chezmoi.sh/
---
apiVersion: iam.aws.upbound.io/v1beta1
kind: UserPolicyAttachment
metadata:
  name: maison.chezmoi.sh-amazonses-n8n
  namespace: kubevault-kvstore
spec:
  forProvider:
    policyArnRef:
      name: maison.chezmoi.sh-amazonses-n8n
    userRef:
      name: maison.chezmoi.sh-amazonses-n8n
---
apiVersion: iam.aws.upbound.io/v1beta1
kind: AccessKey
metadata:
  name: maison.chezmoi.sh-amazonses-n8n
  namespace: kubevault-kvstore
spec:
  forProvider:
    userRef:
      name: maison.chezmoi.sh-amazonses-n8n
  writeConnectionSecretToRef:
    name: apps-n8n-aws-ses
    namespace: kubevault-kvstore
---
# trunk-ignore-all(trivy/KSV113,checkov/CKV2_K8S_5): accessing to this secret is required
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kubevault:kubernetes.maison.chezmoi.sh:n8n-ses
  namespace: kubevault-kvstore
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    resourceNames:
      - apps-n8n-aws-ses
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kubevault:kubernetes.maison.chezmoi.sh:n8n-ses
  namespace: kubevault-kvstore
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kubevault:kubernetes.maison.chezmoi.sh:n8n-ses
subjects:
  - kind: ServiceAccount
    name: kubernetes.maison.chezmoi.sh
