# Cloudflare API Token for Cloudflare Ingress
#
# Description:
#   This resource creates a Cloudflare API Token with specific permissions for
#   managing Cloudflare Ingress and Argo Tunnel configurations. The token is used
#   to manage DNS records and tunnel configurations for secure ingress to
#   Kubernetes services.
#
# Permissions:
#   - Zone Read (c8fed203ed3043cba015a93ad1616f1f): Allows reading zone information
#   - DNS Write (4755a26eedb94da69e1066d98aa820be): Allows managing DNS records
#   - Argo Tunnel Write (c07321b023e944ff818fec44d8203567): Allows managing Argo Tunnels
#
# Security:
#   - Token is stored in Kubernetes secrets in the kubevault-kvstore namespace
#   - Access is restricted to specific IP address (176.145.158.72/32)
#   - RBAC rules restrict secret access to the cloudflare-ingress service account
#
# Usage:
#   This token enables Cloudflare Ingress to:
#   - Manage DNS records for service discovery
#   - Create and manage Argo Tunnels for secure ingress
#   - Automatically update DNS records when services change
---
apiVersion: account.cloudflare.crossplane.io/v1alpha1
kind: APIToken
metadata:
  name: maison-chezmoi-sh-cloudflare-ingress
  namespace: crossplane-maisonchezmoish
spec:
  forProvider:
    name: (maison.chezmoi.sh) - Cloudflare ingress
    policy:
      - effect: allow
        permissionGroups:
          - c8fed203ed3043cba015a93ad1616f1f # Zone Read
          - 4755a26eedb94da69e1066d98aa820be # DNS Write
        resources:
          com.cloudflare.api.account.zone.2734d7b22cf00222046320ed3187cb94: "*"
      - effect: allow
        permissionGroups:
          - c07321b023e944ff818fec44d8203567 # Argo Tunnel Write
        resources:
          com.cloudflare.api.account.00736631322131f61ce95f2c235143da: "*"
  writeConnectionSecretToRef:
    name: cloud-cloudflare-maison.chezmoi.sh-cloudflare-ingress
    namespace: kubevault-kvstore

# trunk-ignore-all(trivy/KSV113,checkov/CKV2_K8S_5): accessing to this secret is required
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kubevault:kubernetes.maison.chezmoi.sh:cloudflare-ingress
  namespace: kubevault-kvstore
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["cloud-cloudflare-maison.chezmoi.sh-cloudflare-ingress"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kubevault:kubernetes.maison.chezmoi.sh:cloudflare-ingress
  namespace: kubevault-kvstore
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kubevault:kubernetes.maison.chezmoi.sh:cloudflare-ingress
subjects:
  - kind: ServiceAccount
    name: kubernetes.maison.chezmoi.sh
