# Cloudflare API Token for External DNS
#
# Description:
#   This resource creates a Cloudflare API Token with specific permissions for
#   External DNS to manage DNS records automatically. The token is used by
#   External DNS to create and update DNS records based on Kubernetes service
#   and ingress configurations.
#
# Permissions:
#   - Zone Read (c8fed203ed3043cba015a93ad1616f1f): Allows reading zone information
#   - DNS Write (4755a26eedb94da69e1066d98aa820be): Allows managing DNS records
#
# Security:
#   - Token is stored in Kubernetes secrets in the kubevault-kvstore namespace
#   - Access is restricted to specific IP address (176.145.158.72/32)
#   - RBAC rules restrict secret access to the external-dns service account
#
# Usage:
#   This token enables External DNS to:
#   - Automatically create DNS records for Kubernetes services
#   - Update DNS records when services change
#   - Maintain DNS records in sync with Kubernetes resources
---
apiVersion: account.cloudflare.crossplane.io/v1alpha1
kind: APIToken
metadata:
  name: maison-chezmoi-sh-external-dns
  namespace: crossplane-maisonchezmoish
spec:
  forProvider:
    name: (maison.chezmoi.sh) - External DNS
    policy:
      - effect: allow
        permissionGroups:
          - c8fed203ed3043cba015a93ad1616f1f # Zone Read
          - 4755a26eedb94da69e1066d98aa820be # DNS Write
        resources:
          com.cloudflare.api.account.zone.2734d7b22cf00222046320ed3187cb94: "*"
  writeConnectionSecretToRef:
    name: cloud-cloudflare-maison.chezmoi.sh-external-dns
    namespace: kubevault-kvstore

# trunk-ignore-all(trivy/KSV113,checkov/CKV2_K8S_5): accessing to this secret is required
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kubevault:kubernetes.maison.chezmoi.sh:external-dns
  namespace: kubevault-kvstore
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["cloud-cloudflare-maison.chezmoi.sh-external-dns"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kubevault:kubernetes.maison.chezmoi.sh:external-dns
  namespace: kubevault-kvstore
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kubevault:kubernetes.maison.chezmoi.sh:external-dns
subjects:
  - kind: ServiceAccount
    name: kubernetes.maison.chezmoi.sh
