---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml

  # Cloudflare credentials
  - cloudflare.iam.external-dns.yaml
  - cloudflare.iam.cert-manager.yaml
