---
networks:
  atlas:
    name: atlas.chezmoi.sh
    driver: bridge

services:
  vscode:
    build:
      context: .
      dockerfile: Dockerfile
    cap_add:
      - SYS_PTRACE
    command: tail -f /dev/null
    container_name: atlas_vscode
    environment:
      DEVCONTAINER_NETWORK: atlas.chezmoi.sh
      DIRENV_LOG_FORMAT: "" # disable direnv logging
      DOCKER_HOST: unix:///var/run/docker-host.sock
    networks:
      atlas:
    tmpfs:
      - /run
      - /tmp:exec
    volumes:
      - ..:/workspaces/atlas:cached
    working_dir: /workspaces/atlas
