galaxy_info:
  author: Alexandre Nicolaie <xunleii@users.noreply.github.com>
  description: Ansible role to deploy a Kairos cluster on Proxmox VE

  issue_tracker_url: https://github.com/chezmoi-sh/arcane/issues
  license: Apache-2.0

  min_ansible_version: 2.1

  # If this a Container Enabled role, provide the minimum Ansible Container version.
  # min_ansible_container_version:

  galaxy_tags:
    - k3s
    - kairos
    - kubernetes
