---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: authelia
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: default-gateway
      namespace: traefik-system
      sectionName: chezmoi.sh-websecure
  hostnames:
    - sso.chezmoi.sh
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: authelia
          port: 80
