---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: external-secrets
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - clusters:
        selector:
          matchExpressions:
            - key: eso.appset.chezmoi.sh/enable
              operator: NotIn
              values: ["false"]
  template:
    metadata:
      name: "{{ .name }}-external-secrets"
    spec:
      source:
        path: |-
          {{- with index .metadata.annotations "eso.appset.chezmoi.sh/kustomize-with" -}}
            {{ index .metadata.annotations "eso.appset.chezmoi.sh/kustomize-with" }}
          {{- else -}}
            catalog/kustomize/external-secrets-operator/
          {{- end -}}
        targetRevision: main
      destination:
        server: "{{ .server }}"
        namespace: external-secrets-system

      syncPolicy:
        automated:
          prune: true # Prune resources that are no more in the repository
          selfHeal: true # Self-heal resources that are no more in the desired state
