---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: external-dns
    repo: https://kubernetes-sigs.github.io/external-dns/
    releaseName: external-dns-adguard
    namespace: kube-system
    version: 1.16.1
    valuesInline:
      logLevel: debug
      sources:
        # - gateway-grpcroute
        - gateway-httproute
        # - gateway-tcproute
        - gateway-tlsroute
        # - gateway-udproute
        - ingress
        - service
        # - traefik-proxy
      txtOwnerId: kubernetes.nx.chezmoi.sh
      policy: sync

      provider:
        name: webhook
        webhook:
          image:
            repository: ghcr.io/muhlba91/external-dns-provider-adguard
            tag: v8.0.0
          env:
            - name: LOG_LEVEL
              value: debug
            - name: ADGUARD_URL
              value: https://dns.chezmoi.sh
            - name: ADGUARD_USER
              value: "-"
            - name: ADGUARD_PASSWORD
              value: "-"
