---
# This ApplicationSet distributes default configurations to every cluster
# in this organization.
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-configuration
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - clusters: {}
  template:
    metadata:
      name: "{{ .name }}-configuration"
    spec:
      source:
        repoURL: https://github.com/chezmoi-sh/atlas.git
        path: '{{ index .metadata.annotations "argocd.argoproj.io/folder-override" | default (printf "projects/%s" .name) }}/src/infrastructure/kubernetes/default'
        targetRevision: main
      destination:
        server: "{{ .server }}"
        namespace: external-secrets-system
