---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd-system

resources:
  - ../../../../../catalog/kustomize/external-secrets-operator/applicationset.argoproj.io

patches:
  - patch: |-
      - op: replace
        path: /spec/template/spec/project
        value: infrastructure
      - op: replace
        path: /spec/template/spec/syncPolicy
        value:
          automated:
            prune: true
            selfHeal: true
          syncOptions:
            - CreateNamespace=true
            - Delete=confirm
            - Prune=confirm
            - ServerSideApply=true
    target:
      kind: ApplicationSet
