---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd-system

resources:
  - cluster-configuration.applicationset.yaml
  - ../../../../../catalog/argocd/cert-manager
  - ../../../../../catalog/argocd/external-secrets-operator

patches:
  - patch: |-
      - op: replace
        path: /spec/template/spec/project
        value: infrastructure
      - op: replace
        path: /spec/template/spec/sources/0/targetRevision
        value: wip/iron-age_features/move-to-helm
      - op: replace
        path: /spec/template/spec/syncPolicy
        value:
          automated:
            prune: true
            selfHeal: true
          syncOptions:
            - CreateNamespace=true
            - Delete=confirm
            - Prune=confirm
            - ServerSideApply=true
    target:
      kind: ApplicationSet
