---
apiVersion: vault.chezmoi.sh/v1alpha1
kind: LocalClusterVault
metadata:
  name: amiya.akn
spec:
  name: amiya.akn
  additionalPolicies:
    - amiya.akn-crossplane-policy
    - amiya.akn-authelia-policy
