---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Additional policies
  - amiya.akn-crossplane-policy.yaml

  # Configure Vault for all clusters
  - amiya.akn.xclustervault.yaml
