---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - shared.mount.yaml

  # Additional policies
  - amiya.akn-authelia-policy.yaml
  - amiya.akn-crossplane-policy.yaml

  # Configure Vault for all clusters
  - amiya.akn.xclustervault.yaml
