---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - authelia.authbackend.yaml
  - shared.mount.yaml

  # Additional policies
  - policies/amiya.akn-authelia-policy.yaml
  - policies/amiya.akn-crossplane-policy.yaml
  - policies/sso-admin-policy.yaml

  # Configure Vault for all clusters
  - amiya.akn.xclustervault.yaml
