---
apiVersion: vault.vault.upbound.io/v1alpha1
kind: Mount
metadata:
  name: shared
spec:
  deletionPolicy: Orphan
  forProvider:
    description: KV v2 mount for local cluster shared
    options:
      version: "2"
    path: shared
    type: kv
  providerConfigRef:
    name: default
