# AWS User for Authelia
#
# Description:
#   These resources will create an AWS IAM User with the necessary permissions
#   to send emails from the domain chezmoi.sh.
#
# trunk-ignore-all(checkov/CKV2_K8S_5,trivy/KSV113): this is a policy to allow a specific user to use a specific secrets... so it's fine
apiVersion: iam.aws.upbound.io/v1beta1
kind: Policy
metadata:
  annotations:
    crossplane.io/external-name: AutheliaSESSender
  name: amiya.akn.chezmoi.sh-amazonses-authelia
spec:
  forProvider:
    path: /amiya.akn.chezmoi.sh/
    policy: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Sid": "AllowSendingEmails",
            "Effect": "Allow",
            "Action": [
              "ses:SendEmail",
              "ses:SendRawEmail"
            ],
            "Resource": "arn:aws:ses:us-east-1:*:identity/*"
          }
        ]
      }
---
apiVersion: iam.aws.upbound.io/v1beta1
kind: User
metadata:
  annotations:
    crossplane.io/external-name: authelia
  name: amiya.akn.chezmoi.sh-amazonses-authelia
spec:
  forProvider:
    path: /amiya.akn.chezmoi.sh/
---
apiVersion: iam.aws.upbound.io/v1beta1
kind: UserPolicyAttachment
metadata:
  name: amiya.akn.chezmoi.sh-amazonses-authelia
spec:
  forProvider:
    policyArnRef:
      name: amiya.akn.chezmoi.sh-amazonses-authelia
    userRef:
      name: amiya.akn.chezmoi.sh-amazonses-authelia
---
apiVersion: iam.aws.upbound.io/v1beta1
kind: AccessKey
metadata:
  name: amiya.akn.chezmoi.sh-amazonses-authelia
spec:
  forProvider:
    userRef:
      name: amiya.akn.chezmoi.sh-amazonses-authelia
  writeConnectionSecretToRef:
    name: security-sso-authelia-aws-ses
    namespace: kubevault-kvstore
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kubevault:kubernetes.amiya.akn.chezmoi.sh:authelia-ses
  namespace: kubevault-kvstore
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    resourceNames:
      - security-sso-authelia-aws-ses
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kubevault:kubernetes.amiya.akn.chezmoi.sh:authelia-ses
  namespace: kubevault-kvstore
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kubevault:kubernetes.amiya.akn.chezmoi.sh:authelia-ses
subjects:
  - kind: ServiceAccount
    name: kubernetes.amiya.akn.chezmoi.sh
