# Cloudflare API Token for cert-manager
#
# Description:
#   This resource creates a Cloudflare API Token with specific permissions for cert-manager
#   to manage DNS records and zones. The token is used by cert-manager to automatically
#   create and manage DNS-01 challenges for Let's Encrypt certificates.
#
# Permissions:
#   - Zone Read (c8fed203ed3043cba015a93ad1616f1f): Allows reading zone information
#   - DNS Write (4755a26eedb94da69e1066d98aa820be): Allows creating and managing DNS records
#
# Security:
#   The token is stored in a Kubernetes secret in the kubevault-kvstore namespace
#   and is used by cert-manager to validate domain ownership during certificate issuance.
#
# Usage:
#   This token is specifically scoped to the chezmoi.sh domain and is used by
#   cert-manager to automatically create and manage DNS records for SSL/TLS
#   certificate validation.
#
# trunk-ignore-all(checkov/CKV2_K8S_5,trivy/KSV113): this is a policy to allow a specific user to use a specific secrets... so it's fine

---
apiVersion: account.cloudflare.crossplane.io/v1alpha1
kind: APIToken
metadata:
  name: amiyaakn-chezmoi-sh-cert-manager
spec:
  forProvider:
    name: (amiya.akn.chezmoi.sh) - cert-manager
    policy:
      - effect: allow
        permissionGroups:
          - c8fed203ed3043cba015a93ad1616f1f # Zone Read
          - 4755a26eedb94da69e1066d98aa820be # DNS Write
        resources:
          com.cloudflare.api.account.zone.2734d7b22cf00222046320ed3187cb94: "*"
  writeConnectionSecretToRef:
    name: cloud-cloudflare-amiyaakn-certmanager
    namespace: kubevault-kvstore
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kubevault:kubernetes.amiya.akn.chezmoi.sh:cert-manager
  namespace: kubevault-kvstore
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    resourceNames:
      - cloud-cloudflare-amiyaakn-certmanager
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kubevault:kubernetes.amiya.akn.chezmoi.sh:cert-manager
  namespace: kubevault-kvstore
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kubevault:kubernetes.amiya.akn.chezmoi.sh:cert-manager
subjects:
  - kind: ServiceAccount
    name: kubernetes.amiya.akn.chezmoi.sh
