---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: configurations
spec:
  interval: 12h0m0s
  timeout: 5m0s
  retryInterval: 1m0s

  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./projects/maison/src/infrastructure/kubernetes/configs

  dependsOn:
    - name: cert-manager
    - name: external-secrets-operator
    - name: traefik

  prune: true
  wait: false
