---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets-operator
spec:
  interval: 12h0m0s
  timeout: 2m0s
  retryInterval: 1m0s

  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./catalog/fluxcd/external-secrets-operator

  # NOTE: depends on cert-manager to create the webhook certificate
  dependsOn:
    - name: cert-manager

  prune: true
  wait: true
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: kubernetes.maison.chezmoi.sh
spec:
  provider:
    kubernetes:
      auth:
        token:
          bearerToken:
            key: token
            name: kubevault-kubernetes.maison.chezmoi.sh
            namespace: system-catalog
      remoteNamespace: kubevault-kvstore
      server:
        caProvider:
          key: ca.crt
          name: kubevault-kubernetes.maison.chezmoi.sh
          namespace: system-catalog
          type: Secret
        url: https://kubernetes.nx.chezmoi.sh:6443/
