---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system

resources:
  # NOTE: Operators are manually installed using this kustomization to avoid
  #       installing automatically if it is not needed.
  - cert-manager.yaml
  - cloudflare-tunnel-ingress-controller.yaml
  - cloudnative-pg.yaml
  - csi-driver-smb.yaml
  - external-dns.yaml
  - external-secrets-operator.yaml
  - tailscale-operator.yaml
  - traefik.yaml

  # NOTE: Because some configurations requires the operators to be installed,
  #       the configurations are installed using a Flux Kustomization.
  - configs.kustomization.yaml
