---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: traefik
spec:
  interval: 12h0m0s
  timeout: 2m0s
  retryInterval: 1m0s

  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./catalog/fluxcd/traefik

  dependsOn:
    - name: tailscale-operator # NOTE: depends on tailscale-operator to create the Service used to access to resources through Tailscale

  prune: true
  wait: true
