---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/exclude-cloudflare: "true"
  name: n8n-websecure
  namespace: n8n
spec:
  parentRefs:
    - name: default
      namespace: default
  hostnames:
    - n8n.chezmoi.sh
  rules:
    - backendRefs:
        - name: n8n
          port: 80
    - matches:
        - path:
            type: PathPrefix
            value: /presidio/analyz
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /analyz
      backendRefs:
        - name: n8n-analyzer
          port: 80
    - matches:
        - path:
            type: PathPrefix
            value: /presidio/anonymiz
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /anonymiz
      backendRefs:
        - name: n8n-anonymizer
          port: 80
