---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  labels:
    app.kubernetes.io/component: database
    app.kubernetes.io/instance: n8n-database
    app.kubernetes.io/name: n8n
    app.kubernetes.io/part-of: n8n
  name: n8n-database
  namespace: n8n
spec:
  backup:
    barmanObjectStore: &barmanObjectStore
      data:
        compression: bzip2
      destinationPath: s3://cnpg-backups/maison.chezmoi.sh/n8n
      endpointURL: https://s3.chezmoi.sh:9000
      serverName: 01JHBK4N869T0T3Q1BBX673GQ9 # DRP::dst_ulid
      s3Credentials:
        accessKeyId:
          name: cnpg-s3-credentials
          key: access_key_id
        secretAccessKey:
          name: cnpg-s3-credentials
          key: access_secret_key
      wal:
        compression: bzip2
    retentionPolicy: 30d
  bootstrap:
    # initdb:
    #   database: app
    #   owner: app
    recovery:
      source: recoveryBackup
  description: PostgreSQL database dedicated to n8n
  externalClusters:
    - name: recoveryBackup
      barmanObjectStore:
        <<: *barmanObjectStore
        serverName: 01JHBJWT34B203648TQT020A5V # DRP::src_ulid
  instances: 1
  storage:
    size: 5Gi
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  labels:
    app.kubernetes.io/component: backup
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/part-of: n8n
  name: n8n-database
  namespace: n8n
spec:
  schedule: "@daily"
  backupOwnerReference: cluster
  cluster:
    name: n8n-database
