---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: n8n
  namespace: n8n
  labels:
    app.kubernetes.io/instance: n8n
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: n8n
  serviceName: n8n
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: n8n
        network-policy.k8s.io/allow-to-kubernetes-dns: "true"
    spec:
      automountServiceAccountToken: false
      containers:
        # trunk-ignore(trivy/KSV020,trivy/KSV021): n8n seems having some issues when running as non-node user
        - name: n8n
          env:
            # WebUI & deployment configuration
            - name: N8N_EDITOR_BASE_URL
              value: https://n8n.chezmoi.sh
            - name: N8N_HOST
              value: n8n.chezmoi.sh
            - name: VUE_APP_URL_BASE_API
              value: https://n8n.chezmoi.sh

            # Database configuration
            - name: DB_TYPE
              value: postgresdb
            - name: DB_POSTGRESDB_DATABASE_FILE
              value: /run/secrets/n8n/postgres/dbname
            - name: DB_POSTGRESDB_HOST_FILE
              value: /run/secrets/n8n/postgres/host
            - name: DB_POSTGRESDB_PASSWORD_FILE
              value: /run/secrets/n8n/postgres/password
            - name: DB_POSTGRESDB_PORT_FILE
              value: /run/secrets/n8n/postgres/port
            - name: DB_POSTGRESDB_USER_FILE
              value: /run/secrets/n8n/postgres/user

            # SMTP configuration
            - name: N8N_EMAIL_MODE
              value: smtp
            - name: N8N_SMTP_HOST_FILE
              value: /run/secrets/n8n/smtp/aws_ses_host
            - name: N8N_SMTP_PASS_FILE
              value: /run/secrets/n8n/smtp/aws_ses_password
            - name: N8N_SMTP_PORT_FILE
              value: /run/secrets/n8n/smtp/aws_ses_port
            - name: N8N_SMTP_SENDER_FILE
              value: /run/secrets/n8n/smtp/aws_ses_sender
            - name: N8N_SMTP_USER_FILE
              value: /run/secrets/n8n/smtp/aws_ses_username

            # Timezone and locale configuration
            - name: GENERIC_TIMEZONE
              value: Europe/Paris
            - name: N8N_DEFAULT_LOCALE
              value: fr-FR
            - name: TZ
              value: Europe/Paris

            # Security configuration
            - name: NODE_FUNCTION_ALLOW_BUILTIN
              value: "*"
            - name: NODE_FUNCTION_ALLOW_EXTERNAL
              value: "*"

            # Miscellanous configuration
            - name: N8N_DIAGNOSTICS_ENABLED
              value: "false"
            - name: N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS
              value: "true"
            - name: N8N_HIRING_BANNER_ENABLED
              value: "false"
            - name: N8N_TEMPLATES_ENABLED
              value: "true"
          image: docker.n8n.io/n8nio/n8n:1.98.1@sha256:1d35d503d0ec6586d55ab7d0eb34d9bafdf9a908e3c5127020ad851ad3b0e629
          livenessProbe:
            httpGet:
              path: /
              port: http
          ports:
            - name: http
              containerPort: 5678
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            requests:
              cpu: 100m
              memory: 1Gi
            limits:
              memory: 1Gi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            seccompProfile:
              type: RuntimeDefault
          volumeMounts:
            - name: cnpg-config
              mountPath: /run/secrets/n8n/postgres
              readOnly: true
            - name: smtp-config
              mountPath: /run/secrets/n8n/smtp
              readOnly: true
            - name: n8n-persistent
              mountPath: /home/node/.n8n
            - name: tmpdir
              mountPath: /home/node
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      volumes:
        - name: cnpg-config
          secret:
            secretName: n8n-database-app
        - name: smtp-config
          secret:
            secretName: n8n-smtp-credentials
        - name: n8n-persistent
          persistentVolumeClaim:
            claimName: n8n-persistent
        - name: tmpdir
          emptyDir: {}
  volumeClaimTemplates:
    - metadata:
        name: n8n-persistent
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: n8n
  namespace: n8n
  labels:
    app.kubernetes.io/instance: n8n
spec:
  selector:
    app.kubernetes.io/instance: n8n
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: n8n-smtp
  namespace: n8n
spec:
  data:
    - remoteRef:
        key: apps-n8n-aws-ses
        property: username
      secretKey: aws_ses_username
    - remoteRef:
        key: apps-n8n-aws-ses
        property: password
      secretKey: aws_ses_password
  secretStoreRef:
    kind: ClusterSecretStore
    name: kubernetes.maison.chezmoi.sh
  target:
    name: n8n-smtp-credentials
    template:
      type: Opaque
      engineVersion: v2
      data:
        aws_ses_host: email-smtp.us-east-1.amazonaws.com
        aws_ses_password: "{{ .aws_ses_password }}"
        aws_ses_port: "587"
        aws_ses_sender: n8n <noreply@amazonses.chezmoi.sh>
        aws_ses_username: "{{ .aws_ses_username }}"
