---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: seed
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: seed
  sources:
    - ref: origin
      repoURL: https://github.com/chezmoidotsh/arcane.git
      targetRevision: main
      path: projects/amiya.akn/src/apps/*argocd/seed.apps
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - Delete=confirm
      - Prune=confirm
      - ServerSideApply=true
