---
# This Helm values file contains all default values used by the Cert-Manager
# Helm chart.

# Install and updates the CRDs as part of the Helm install/upgrade process.
crds:
  enabled: true
  keep: false

# Enforce the security context for the operator
securityContext:
  fsGroup: 34983
  runAsGroup: 34983
  runAsNonRoot: true
  runAsUser: 34983
  seccompProfile:
    type: RuntimeDefault
containerSecurityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
