---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

labels:
  - pairs:
      app.kubernetes.io/part-of: cert-manager
      app.kubernetes.io/managed-by: kustomize
    includeSelectors: false
    includeTemplates: true

helmCharts:
  - name: cert-manager
    repo: https://charts.jetstack.io
    releaseName: cert-manager
    namespace: cert-manager-system
    version: v1.17.1
    valuesFile: cert-manager.helm-values.yaml
