---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: jellyfin
  namespace: jellyfin
spec:
  interval: 24h0m0s # NOTE: don't need to check for updates often
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  url: oci://ghcr.io/m0nsterrr/helm-charts/jellyfin
  ref:
    semver: ">=1.0.0"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: jellyfin
spec:
  interval: 12h0m0s
  chartRef:
    kind: OCIRepository
    name: jellyfin
    namespace: jellyfin

  # Customisation of the HelmRelease behaviour
  driftDetection: { mode: warn }
  test: { enable: false } # NOTE: bugged on this chart
  rollback: { cleanupOnFail: true, recreate: true }

  releaseName: jellyfin
  values:
    # NOTE: enhance security context
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      readOnlyRootFilesystem: true
      runAsGroup: 64710
      runAsNonRoot: true
      runAsUser: 64710

    podSecurityContext:
      runAsGroup: 64710
      runAsNonRoot: true
      runAsUser: 64710
      fsGroup: 64710
      seccompProfile:
        type: RuntimeDefault
      supplementalGroups: [65534] # NOTE: allow read access to NFS volumes

    # NOTE: add NFS media volumes
    volumes:
      - name: movies
        nfs:
          server: nas.chezmoi.sh
          path: /mnt/zp1cs01/media/movies
          readOnly: true
      - name: tvshows
        nfs:
          server: nas.chezmoi.sh
          path: /mnt/zp1cs01/media/tvshows
          readOnly: true
      - name: musics
        nfs:
          server: nas.chezmoi.sh
          path: /mnt/zp1cs01/media/musics
          readOnly: true
      - name: animes
        nfs:
          server: nas.chezmoi.sh
          path: /mnt/zp1cs01/media/animes
          readOnly: true
      - name: tmpdir
        emptyDir: {}
    volumeMounts:
      - name: movies
        mountPath: /media/movies
        readOnly: true
      - name: tvshows
        mountPath: /media/tvshows
        readOnly: true
      - name: musics
        mountPath: /media/musics
        readOnly: true
      - name: animes
        mountPath: /media/animes
        readOnly: true
      - name: tmpdir
        mountPath: /tmp
