---
# Source: traefik/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: 
  labels: 
    app.kubernetes.io/name: traefik-default
    app.kubernetes.io/instance: default
    app.kubernetes.io/version: "v3.1.2"
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: traefik-0.1.0
  name: traefik-default
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels: 
      app.kubernetes.io/instance: default
      app.kubernetes.io/version: "v3.1.2"
  template:
    # missing pod annotations/labels
    metadata:
      labels: 
        app.kubernetes.io/instance: default
        app.kubernetes.io/version: "v3.1.2"
    spec:
      containers:
      - name: traefik
        image: :v3.1.2
        imagePullPolicy: IfNotPresent
        # generates ports from traefik configuration
        # generates flags from traefik configuration (converts to --flag value)
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: [ALL]
          privileged: false
          readOnlyRootFilesystem: true
      securityContext:
        fsGroup: 22760
        runAsGroup: 22760
        runAsNonRoot: true
        runAsUser: 44782
