---
# Source: traefik/templates/services.yaml
apiVersion: v1
kind: Service
metadata:
  annotations: 
    {}
  labels: 
    app.kubernetes.io/instance: default
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: traefik-default
    app.kubernetes.io/version: v3.1.2
    helm.sh/chart: traefik-0.1.0
  name: traefik-default
  namespace: validations
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: default
    app.kubernetes.io/version: "v3.1.2"
    helm.sh/chart: traefik-0.1.0
  ports:
    - name: traefik
      port: 9000
      targetPort: traefik
      protocol: TCP
      appProtocol: http
