---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
spec:
  destination:
    namespace: external-secrets-system
    # server: {{ .server }}
  project: system
  sources:
    - ref: origin
      repoURL: https://github.com/chezmoi-sh/atlas.git
      targetRevision: main
    - chart: external-secrets
      helm:
        ignoreMissingValueFiles: true
        releaseName: external-secrets
        valueFiles:
          - $origin/defaults/kubernetes/external-secrets/helm/default.helmvalues.yaml
          - $origin/defaults/kubernetes/external-secrets/helm/hardened.helmvalues.yaml
          - $origin/defaults/kubernetes/external-secrets/helm/kubevault.helmvalues.yaml
          # - $origin/projects/{{ .name }}/src/infrastructure/kubernetes/external-secrets/override.helmvalues.yaml
          # - $origin/projects/{{ index .metadata.annotations "device.tailscale.com/hostname" | default .name }}/src/infrastructure/kubernetes/external-secrets/override.helmvalues.yaml
      repoURL: https://charts.external-secrets.io/
      targetRevision: 0.14.4
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - Delete=confirm
      - Prune=confirm
      - ServerSideApply=true
