---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nx-dns

resources:
  - namespace.yaml

  - ../../base/adguardhome
  - adguardhome-ingress.yaml
  - adguardhome-netpolicy.yaml
