# NOTE: because Traefik is configured to use the Gateway API, we need to import
#       the experimental Gateway API CRDs.
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: kubernetes-sigs-gateway-api
  namespace: traefik-system
spec:
  interval: 24h0m0s
  ref:
    semver: ">= 1.0.0, < 2.0.0"
  url: https://github.com/kubernetes-sigs/gateway-api.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gateway-api-crds
  namespace: traefik-system
spec:
  interval: 24h0m0s
  sourceRef:
    kind: GitRepository
    name: kubernetes-sigs-gateway-api
  path: ./config/crd/experimental

  prune: true
  wait: true
