---
apiVersion: vault.vault.upbound.io/v1alpha1
kind: Policy
metadata:
  name: global-eso-policy
spec:
  forProvider:
    name: global-eso-policy
    policy: |
      # Allow ESO to read all certificates on the shared mount
      path "shared/data/certificates/*" {
        capabilities = ["read"]
      }

  providerConfigRef:
    name: default
