# trunk-ignore-all(checkov/CKV_SECRET_6): no secret here
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-credentials
  namespace: cloudflare-system
spec:
  refreshInterval: 1h
  target:
    name: cloudflare-credentials
  data:
    - secretKey: accountID
      remoteRef: { key: "", property: "" }
    - secretKey: apiToken
      remoteRef: { key: "", property: "" }
    - secretKey: tunnelName
      remoteRef: { key: "", property: "" }
