---
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: traefik-gateway
spec:
  controllerName: traefik.io/gateway-controller
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: default-gateway
  namespace: traefik-system
spec:
  gatewayClassName: traefik-gateway
  listeners:
    - name: web
      protocol: TCP
      port: 80
      allowedRoutes:
        namespaces:
          from: All
