---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: traefik
namespace: traefik-system
resources:
  # install Gateway API CRDs v1.1.0
  - https://github.com/kubernetes-sigs/gateway-api.git//config/crd/experimental?ref=v1.1.0

  - namespace.yaml
  - traefik.yaml
  - default-gateway.yaml
