---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-sops
  labels:
    app.kubernetes.io/part-of: argocd
spec:
  data:
    - remoteRef:
        key: security-sops-age-keys
        property: security-age-argocd
      secretKey: age-key
  secretStoreRef:
    kind: ClusterSecretStore
    name: kubevault
  target:
    name: argocd-sops-age-key
    template:
      type: Opaque
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd
