---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
  # Configure ArgoCD
  - argocd.oidc-credentials.externalsecret.yaml
  - argocd.ingress.yaml
  - argocd.appprojects.yaml
  - seed.application.yaml

  # Install Argotails that manages all Tailscale clusters
  # secrets based on Tailscale's devices
  - https://github.com/chezmoi-sh/argotails.git//deploy/manifests/default?ref=v0.1.5
  - argotails.ts-secrets.externalsecret.yaml

helmCharts:
  - name: argo-cd
    repo: https://argoproj.github.io/argo-helm
    releaseName: argocd
    version: 7.8.23
    valuesFile: argocd.helm-values/default.yaml
    additionalValuesFiles:
      - argocd.helm-values/hardened.yaml
      - argocd.helm-values/extensions.yaml
      - argocd.helm-values/ksops-addon.yaml
      - argocd.helm-values/tailscale-addon.yaml

patches:
  - patch: |
      - op: replace
        path: /spec/template/spec/containers/0/args/2
        value: --ts.device-filter=kubernetes-cluster
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: tail831c5d.ts.net
    target:
      name: argotails
      kind: Deployment
