# ┌───────────────────────────────────────────────────────────────────────────┐
# │                           Service Catalog Entry                           │
# ├───────────────────────────────────────────────────────────────────────────┤
# │ name: csi-driver-smb                                                      │
# │ description: |                                                            │
# │   CSI Driver to allow SMB shares to be mounted in Kubernetes.             │
# │ tags:                                                                     │
# │   - csi                                                                   │
# │   - smb                                                                   │
# │   - storage                                                               │
# │ links:                                                                    │
# │   - title: CSI Driver for SMB Documentation                               │
# │     url: https://github.com/kubernetes-csi/csi-driver-smb                 │
# └───────────────────────────────────────────────────────────────────────────┘
# trunk-ignore-all(trivy/KSV037): CSI driver should be installed in the kube-system namespace
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: csi-driver-smb
  namespace: kube-system
spec:
  interval: 24h0m0s # NOTE: don't need to check for updates often
  url: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/master/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: csi-driver-smb
  namespace: kube-system
spec:
  interval: 12h0m0s
  chart:
    spec:
      chart: csi-driver-smb
      version: 1.16.0
      sourceRef:
        kind: HelmRepository
        name: csi-driver-smb
        namespace: kube-system

  # Customisation of the HelmRelease behaviour
  driftDetection: { mode: warn }
  test: { enable: true }
  rollback: { cleanupOnFail: true, recreate: true }

  releaseName: csi-driver-smb
