---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tailscale-credentials
  namespace: tailscale-system
spec:
  refreshInterval: 1h
  target:
    name: operator-oauth
  data:
    - secretKey: client_id
      remoteRef: { key: "", property: "" }
    - secretKey: client_secret
      remoteRef: { key: "", property: "" }
