# ┌───────────────────────────────────────────────────────────────────────────┐
# │                           Service Catalog Entry                           │
# ├───────────────────────────────────────────────────────────────────────────┤
# │ name: tailscale                                                           │
# │ description: |                                                            │
# │   Tailscale makes creating software-defined networks easy: securely       │
# │   connecting users, services, and devices.                                │
# │ tags:                                                                     │
# │   - vpn                                                                   │
# │   - network                                                               │
# │ links:                                                                    │
# │   - title: Tailscale Website                                              │
# │     url: https://tailscale.com/                                           │
# │   - title: Tailscale Documentation                                        │
# │     url: https://tailscale.com/kb/                                        │
# │   - title: Tailscale Helm Chart                                           │
# │     url: https://pkgs.tailscale.com/helmcharts                            │
# └───────────────────────────────────────────────────────────────────────────┘
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: tailscale-operator
  namespace: tailscale-system
spec:
  interval: 24h0m0s # NOTE: don't need to check for updates often
  url: https://pkgs.tailscale.com/helmcharts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale-operator
  namespace: tailscale-system
spec:
  interval: 12h0m0s
  chart:
    spec:
      chart: tailscale-operator
      version: 1.78.3
      sourceRef:
        kind: HelmRepository
        name: tailscale-operator
        namespace: tailscale-system

  # Customisation of the HelmRelease behaviour
  driftDetection: { mode: warn }
  test: { enable: true }
  rollback: { cleanupOnFail: true, recreate: true }

  releaseName: tailscale-operator
  values:
    installCRDs: true
