---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - ../../../../../../catalog/kustomize/tun-device-plugin

patches:
  - path: restricted.proxyclass.yaml

  # (SecOps) Network Policies
  - path: security/allow-to-kubernetes-api.networkpolicy.yaml
