---
apiVersion: v2
name: traefik
description: Traefik based Kubernetes Ingress and Gateway controller
type: application
version: 0.1.0
appVersion: v3.1.2
kubeVersion: ">=1.30.0-0"
home: https://traefik.io
icon: ...
keywords:
  - kubernetes
  - ingress
  - gateway
  - networking
  - nix-container
sources:
  - https://github.com/chezmoi-sh/atlas
  - https://github.com/traefik/traefik
maintainers:
  - name: chezmoi.sh (labs)
    email: xunleii@users.noreply.github.com
annotations:
  artifacthub.io/chategory: networking
  artifacthub.io/changes: |
    - kind: added
      description: 🎉 Initial release
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/links: |
    - name: Application source
      url: https://github.com/traefik/traefik
  artifacthub.io/prerelease: "true"
  artifacthub.io/recommendations: ''
  artifacthub.io/signKey: ''
