---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-traefik-to-cluster
  annotations:
    networkpolicy.kubernetes.io/description: >-
      Allow egress traffic from Traefik ingress pods to in-cluster services.
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: traefik
  policyTypes:
    - Egress
  egress:
    - to:
        - namespaceSelector: {}
