---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-traefik-to-kubernetes-api
  annotations:
    networkpolicy.kubernetes.io/description: >-
      Allow egress traffic from Traefik ingress pods to the Kubernetes API.
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: traefik
  policyTypes:
    - Egress
  egress:
    - ports:
        - port: 443
          protocol: TCP
      to:
        - namespaceSelector:
            matchExpressions: # NOTE: This is a workaround to avoid Kustomization `labels` being applied to the NetworkPolicy
              - key: kubernetes.io/metadata.name
                operator: In
                values:
                  - kube-system
          podSelector:
            matchExpressions: # NOTE: This is a workaround to avoid Kustomization `labels` being applied to the NetworkPolicy
              - key: k8s-app
                operator: In
                values:
                  - kube-apiserver
