# ┌───────────────────────────────────────────────────────────────────────────────────────────┐
# │                                   Service Catalog Entry                                   │
# ├───────────────────────────────────────────────────────────────────────────────────────────┤
# │ name: external-secrets                                                                    │
# │ description: |                                                                            │
# │   External Secrets is a Kubernetes controller that allows you to fetch                    │
# │   secrets from AWS Secrets Manager, Google Secret Manager, Azure Key                      │
# │   Vault, and more.                                                                        │
# │ tags:                                                                                     │
# │   - secret                                                                                │
# │ links:                                                                                    │
# │   - title: External Secrets Website                                                       │
# │     url: https://external-secrets.io/                                                     │
# │   - title: External Secrets Documentation                                                 │
# │     url: https://external-secrets.io/docs/                                                │
# │   - title: External Secrets Helm Chart                                                    │
# │     url: https://artifacthub.io/packages/helm/external-secrets-operator/external-secrets  │
# └───────────────────────────────────────────────────────────────────────────────────────────┘
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: external-secrets-operator
  namespace: external-secrets-system
spec:
  interval: 24h0m0s # NOTE: don't need to check for updates often
  url: https://charts.external-secrets.io/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets-operator
  namespace: external-secrets-system
spec:
  interval: 12h0m0s
  chart:
    spec:
      chart: external-secrets
      version: 0.11.0
      sourceRef:
        kind: HelmRepository
        name: external-secrets-operator
        namespace: external-secrets-system

  # Customisation of the HelmRelease behaviour
  driftDetection: { mode: warn }
  test: { enable: true }
  rollback: { cleanupOnFail: true, recreate: true }

  releaseName: external-secrets-operator
  values:
    webhook:
      cert-manager:
        enabled: true
        issuerRef:
          group: cert-manager.io
          kind: Issuer
          name: external-secrets-webhook
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: external-secrets-webhook
  namespace: external-secrets-system
spec:
  selfSigned: {}
