# Cloudflare credentials for chezmoi.sh
#
# Description:
#   This ExternalSecret creates a secret that will be used by the Cloudflare
#   provider.
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-credentials
spec:
  refreshInterval: 720h # 30 days
  secretStoreRef:
    kind: ClusterSecretStore
    name: kubevault
  target:
    name: cloudflare-credentials
    template:
      type: Opaque
      engineVersion: v2
      data:
        credentials: '{"email":"{{ .email }}","api_key":"{{ .api_key }}"}'
  data:
    - secretKey: email
      remoteRef:
        key: cloud-cloudflare-crossplane-chezmoi-sh
        property: email
    - secretKey: api_key
      remoteRef:
        key: cloud-cloudflare-crossplane-chezmoi-sh
        property: api_key
