---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      app.kubernetes.io/name: affine
    includeTemplates: true
    includeSelectors: true
  - pairs:
      app.kubernetes.io/managed-by: fluxcd
      app.kubernetes.io/part-of: productivity-workspace
    includeTemplates: true

configMapGenerator:
  - name: affine-configuration
    namespace: affine
    options:
      disableNameSuffixHash: true
    files:
      - config/affine.js

resources:
  - httproute.yaml
  - namespace.yaml
  - vpn.yaml
  - workload.affine.yaml
  - workload.database.yaml
  - workload.redis.yaml
