---
# Source: traefik/templates/rbac/clusterrolebindings.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations: 
  labels: 
    app.kubernetes.io/name: traefik-default
    app.kubernetes.io/instance: default
    app.kubernetes.io/version: "v3.1.2"
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: traefik-0.1.0
  name: traefik:default-default:traefik
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: traefik:default-default:traefik
subjects:
  - kind: ServiceAccount
    name: traefik-default
    namespace: default
