---
# Source: traefik/templates/rbac/serviceaccounts.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations: 
  labels: 
    app.kubernetes.io/name: traefik-default
    app.kubernetes.io/instance: default
    app.kubernetes.io/version: "v3.1.2"
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: traefik-0.1.0
  name: traefik-default
  namespace: default
