---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  annotations:
    argocd.argoproj.io/description: |
      This ApplicationSet is responsible for automatically deploying all
      applications and configurations inside the targeted cluster,
      depending on existing cluster definitions.
  name: applications
spec:
  ignoreApplicationDifferences:
    - jsonPointers:
        - /spec/ignoreDifferences
        - /spec/source/targetRevision
        - /spec/syncPolicy/automated
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
          - list: { elements: [] } # NOTE: this list will be populated by the `seed` ApplicationSet with the cluster metadata
          - git:
              repoURL: https://github.com/chezmoi-sh/atlas.git
              revision: migration/move-nx-to-amiya.akn
              directories:
                - path: projects/{{ index .metadata.annotations "device.tailscale.com/hostname" | default .name }}/src/apps/*
  template:
    metadata:
      annotations:
        # All applications should be deployed after system applications
        argocd.argoproj.io/sync-wave: "100"
      name: '{{ .path.basename | trimPrefix "*" }}'
    spec:
      destination:
        server: "{{ .server }}"
        namespace: '{{ .path.basename | trimPrefix "*" }}'
      project: applications
      sources:
        - repoURL: https://github.com/chezmoi-sh/atlas.git
          path: "{{ .path.path }}"
          targetRevision: migration/move-nx-to-amiya.akn
  templatePatch: |
    spec:
      syncPolicy:
        {{ if hasPrefix "*" .path.basename }}
        syncOptions:
          - CreateNamespace=true
          - Delete=confirm
          - Prune=confirm
          - ServerSideApply=true
        {{ else }}
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
        {{ end }}
