---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
spec:
  destination:
    namespace: external-secrets-system
    # server: {{ .server }}
  project: system
  sources:
    - ref: origin
      repoURL: https://github.com/chezmoidotsh/arcane.git
      targetRevision: main
      path: defaults/kubernetes/external-secrets/kustomize

      kustomize:
        {}

        # patches:
        #   - patch: |-
        #       - op: replace
        #         path: /spec/provider/vault/path
        #         value: secret/data/{{ index .metadata.annotations "device.tailscale.com/hostname" | default .name }}
        #       - op: replace
        #         path: /spec/provider/vault/auth/kubernetes/mountPath
        #         value: {{ index .metadata.annotations "device.tailscale.com/hostname" | default .name }}
        #       - op: replace
        #         path: /spec/provider/vault/auth/kubernetes/role
        #         value: {{ index .metadata.annotations "device.tailscale.com/hostname" | default .name }}-eso-role
        #     target:
        #       kind: ClusterSecretStore
        #       name: vault.chezmoi.sh

    - chart: external-secrets
      helm:
        ignoreMissingValueFiles: true
        releaseName: external-secrets
        valueFiles:
          - $origin/defaults/kubernetes/external-secrets/helm/default.helmvalues.yaml
          - $origin/defaults/kubernetes/external-secrets/helm/hardened.helmvalues.yaml
          # - $origin/projects/{{ .name }}/src/infrastructure/kubernetes/external-secrets/override.helmvalues.yaml
          # - $origin/projects/{{ index .metadata.annotations "device.tailscale.com/hostname" | default .name }}/src/infrastructure/kubernetes/external-secrets/override.helmvalues.yaml
      repoURL: https://charts.external-secrets.io/
      targetRevision: 0.18.0
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - Delete=confirm
      - Prune=confirm
      - ServerSideApply=true
