---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
spec:
  destination:
    namespace: traefik-system
    # server: {{ .server }}
  project: system
  sources:
    - ref: origin
      repoURL: https://github.com/chezmoidotsh/arcane.git
      targetRevision: main
      path: defaults/kubernetes/traefik/kustomize

      kustomize:
        {}
        # components:
        #   - projects/{{ .name }}/src/infrastructure/kubernetes/traefik/
        #   - projects/{{ index .metadata.annotations "device.tailscale.com/hostname" | default .name }}/src/infrastructure/kubernetes/traefik/
        # ignoreMissingComponents: true
    - chart: traefik
      helm:
        ignoreMissingValueFiles: true
        releaseName: traefik
        skipCrds: true # NOTE: skip CRDs because they are installed separately
        valueFiles:
          - $origin/defaults/kubernetes/traefik/helm/default.helmvalues.yaml
          - $origin/defaults/kubernetes/traefik/helm/hardened.helmvalues.yaml
          # - $origin/projects/{{ .name }}/src/infrastructure/kubernetes/traefik/override.helmvalues.yaml
          # - $origin/projects/{{ index .metadata.annotations "device.tailscale.com/hostname" | default .name }}/src/infrastructure/kubernetes/traefik/override.helmvalues.yaml
      repoURL: https://traefik.github.io/charts
      targetRevision: 34.5.0
    - chart: traefik-crds
      helm:
        ignoreMissingValueFiles: true
        releaseName: traefik-crds
      repoURL: https://traefik.github.io/charts
      targetRevision: 1.6.0

    - repoURL: https://github.com/kubernetes-sigs/gateway-api.git
      targetRevision: v1.2.1
      path: config/crd/experimental
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - Delete=confirm
      - Prune=confirm
      - ServerSideApply=true
