---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authelia-credentials
spec:
  refreshInterval: 15s
  secretStoreRef:
    kind: ClusterSecretStore
    name: kubevault
  target:
    name: authelia-secrets
  dataFrom:
    - extract:
        key: security-sso-authelia
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authelia-aws-smtp
spec:
  refreshInterval: 15s
  secretStoreRef:
    kind: ClusterSecretStore
    name: kubevault
  target:
    name: authelia-aws-ses
  data:
    - secretKey: notifier_smtp_username
      remoteRef:
        key: security-sso-authelia-aws-ses
        property: username
    - secretKey: notifier_smtp_password
      remoteRef:
        key: security-sso-authelia-aws-ses
        property: attribute.ses_smtp_password_v4
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authelia-oidc-linkding
spec:
  refreshInterval: 15s
  secretStoreRef:
    kind: ClusterSecretStore
    name: kubevault
  target:
    name: authelia-oidc-linkding
  data:
    - secretKey: oidc_client_linkding
      remoteRef:
        key: security-sso-oidc-clients-linkding
        property: oidc_configuration
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authelia-oidc-proxmox
spec:
  refreshInterval: 15s
  secretStoreRef:
    kind: ClusterSecretStore
    name: kubevault
  target:
    name: authelia-oidc-proxmox
  data:
    - secretKey: oidc_client_proxmox
      remoteRef:
        key: security-sso-oidc-clients-proxmox
        property: oidc_configuration
