---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ldaps.chezmoi.sh
spec:
  secretName: ldaps.chezmoi.sh-certificate

  dnsNames:
    - ldaps.chezmoi.sh
  duration: 2160h # 90d
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  renewBefore: 360h # 15d
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: ldaps-gateway
spec:
  gatewayClassName: traefik-gateway
  listeners:
    - name: ldaps
      hostname: ldaps.chezmoi.sh
      protocol: TLS
      port: 636
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: ldaps.chezmoi.sh-certificate
      allowedRoutes:
        namespaces:
          from: Same
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TLSRoute
metadata:
  name: ldaps-tlsroute
spec:
  parentRefs:
    - kind: Gateway
      name: ldaps-gateway
      sectionName: ldaps
  hostnames:
    - ldaps.chezmoi.sh
  rules:
    - backendRefs:
        - kind: Service
          name: yaldap
          port: 389
