---
apiVersion: tailscale.com/v1alpha1
kind: Connector
metadata:
  name: homelab-subnet
spec:
  hostname: homelab-subnet-connector
  subnetRouter:
    advertiseRoutes:
      - 10.0.0.30/32 # nex·rpi
      - 10.0.0.31/32 # Home Assistant
      - 10.0.0.89/32 # NAS (TrueNAS)
