---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tailscale-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: kubevault
  target:
    name: operator-oauth
  data:
    - secretKey: client_id
      remoteRef:
        key: cloud-tailscale-kubernetes-nx-chezmoi-sh
        property: operator-oauth-client-id
    - secretKey: client_secret
      remoteRef:
        key: cloud-tailscale-kubernetes-nx-chezmoi-sh
        property: operator-oauth-client-secret
