---
# This YAML file defines the default Helm values for configuring Tailscale Operator
operatorConfig:
  # For my own use, I use the tag `tag:kubernetes-cluster` to identify the device
  # that is running the Tailscale operator.
  defaultTags:
    - tag:kubernetes-cluster

proxyConfig:
  # Like the operator, I use the tag `tag:kubernetes-apps` to identify the
  # devices that are running the Tailscale ingress proxy.
  defaultTags: tag:kubernetes-apps

apiServerProxyConfig:
  # By default, the API server proxy mode is enabled. This allows Tailscale to
  # act as a proxy for the Kubernetes API server, which is the default behavior
  # for all of my clusters.
  mode: "true"
