---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TLSRoute
metadata:
  name: ldaps-tlsroute
spec:
  parentRefs:
    - kind: Gateway
      name: ldaps-gateway
      namespace: traefik-system
      sectionName: ldaps
  hostnames:
    - ldaps.chezmoi.sh
  rules:
    - backendRefs:
        - kind: Service
          name: yaldap
          port: 389
