---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  labels:
    app.kubernetes.io/instance: yaldap-sso
    app.kubernetes.io/name: yaldap
    app.kubernetes.io/part-of: sso
    app.kubernetes.io/version: v0.2.0
  name: yaldap-backend
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: kubevault
  target:
    name: yaldap-backend
  data:
    - secretKey: backend.yaml
      remoteRef:
        key: security-sso-yaldap
        property: configuration
