---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/chezmoidotsh/arcane.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 6h0m0s
  timeout: 5m0s
  retryInterval: 1m0s

  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./projects/maison/src/clusters/production/

  wait: true
  prune: false # Do not delete resources on suppression (it will remove flux-system)
