---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-to-kube-dns
  annotations:
    app.kubernetes.io/part-of: sso
    networkpolicy.kubernetes.io/description: >-
      Allow egress traffic from sso pods to kube-dns on port 53 (DNS).
spec:
  podSelector: {}
  policyTypes:
    - Egress
  egress:
    - to:
        - namespaceSelector:
            matchExpressions: # NOTE: This is a workaround to avoid Kustomization `labels` being applied to the NetworkPolicy
              - key: kubernetes.io/metadata.name
                operator: In
                values:
                  - kube-system
        - podSelector:
            matchExpressions: # NOTE: This is a workaround to avoid Kustomization `labels` being applied to the NetworkPolicy
              - key: k8s-app
                operator: In
                values:
                  - kube-dns
      ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
