---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-intra-namespace
  annotations:
    app.kubernetes.io/part-of: sso
    networkpolicy.kubernetes.io/description: >-
      Allow all ingress and egress traffic between pods within the sso namespace.
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector: {}
  egress:
    - to:
        - podSelector: {}
