---
# Hardened values for Traefik
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Security context
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop: [ALL]
  readOnlyRootFilesystem: true
  seccompProfile:
    type: RuntimeDefault

# Pod security context
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 39483
  runAsGroup: 39483
