---
name: 📦 Build Kairos bundles

on:
  pull_request:
    paths: ["catalog/kairos-bundles/**"]
  push:
    branches: [main]
    paths: ["catalog/kairos-bundles/**"]

permissions:
  contents: read
  packages: write

jobs:
  find_updated_apps:
    name: 📄 List updated bundles
    runs-on: ubuntu-latest
    outputs:
      updated_apps: ${{ steps.list_bundles.outputs.updated }}
    steps:
      - name: ⬇️ Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: 📄 List updated bundles
        id: list_bundles
        run: |
          (
            echo -n 'updated='
            git diff --name-only "${FROM}" "${TO}" | grep 'catalog/kairos-bundles/' | cut -d'/' -f3 | sort --unique \
            | jq --slurp --raw-input '. | split("\n") | map(select(. != ""))' --compact-output
          ) >> "${GITHUB_OUTPUT}"
        env:
          FROM: ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }}
          TO: ${{ github.event.pull_request.head.sha }}

  build_bundle:
    name: 🏗️ Build bundle (${{ matrix.bundle }})
    needs: find_updated_apps
    runs-on: ubuntu-latest
    strategy:
      matrix:
        bundle: ${{ fromJson(needs.find_updated_apps.outputs.updated_apps) }}
    steps:
      - name: ⬇️ Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: 🛠️ Set up QEMU
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3.6.0
      - name: 🛠️ Set up Docker Buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.10.0

      - name: 🏗️ Build bundle (${{ matrix.bundle }})
        uses: docker/build-push-action@471d1dc4e07e5cdedd4c2171150001c434f0b7a4 # v6.15.0
        with:
          annotations: |
            org.opencontainers.image.title="${{ matrix.bundle }} (kairos bundle)"
            org.opencontainers.image.source="https://${{ github.repository }}/blob/${{ github.sha }}/catalog/kairos-bundles/${{ matrix.bundle }}"
            org.opencontainers.image.description="Kairos bundle for ${{ matrix.bundle }}"
          context: catalog/kairos-bundles/${{ matrix.bundle }}
          file: catalog/kairos-bundles/${{ matrix.bundle }}/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          provenance: mode=max
          push: ${{ github.event_name == 'push' }}
          sbom: true
          tags: ghcr.io/${{ github.repository_owner }}/kairos-bundles:${{ matrix.bundle }}
        env:
          SOURCE_DATE_EPOCH: 0
