---
name: 🏷️ Sync Github labels

on:
  push:
    branches: [main]
    paths:
      [.github/labels.yaml, ".github/workflows/push,schedule.sync-labels.yaml"]
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

permissions: {}

jobs:
  labeler:
    name: 🏷️ Labeler
    permissions:
      issues: write
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
      - name: 🏷️ Sync Github labels with the definition
        uses: brpaz/action-label-syncer@32e516ae73bbf7c7c0548897be07080795336e15 # main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          manifest: .github/labels.yaml
          prune: true
