---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: tailscale-operator
    repo: https://pkgs.tailscale.com/helmcharts
    releaseName: tailscale-operator
    version: 1.80.3
    valuesInline:
      installCRDs: true
