---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argotails-secrets
  labels:
    app.kubernetes.io/part-of: argocd
spec:
  data:
    - remoteRef:
        key: cloud-tailscale-amiyaakn-argocd
        property: argotails-oauth-client-secret
      secretKey: authkey
  secretStoreRef:
    kind: ClusterSecretStore
    name: kubevault
  target:
    name: argotails-secrets
