---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-tailscale
  labels:
    app.kubernetes.io/part-of: argocd
spec:
  data:
    - remoteRef:
        key: cloud-tailscale-amiyaakn-argocd
        property: argocd-auth-key
      secretKey: authkey
  secretStoreRef:
    kind: ClusterSecretStore
    name: kubevault
  target:
    name: argocd-tailscale-creds
