---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-github
  labels:
    app.kubernetes.io/part-of: argocd
spec:
  data:
    - remoteRef:
        key: cloud-github-app-argocd
        property: app_id
      secretKey: githubAppID # NOTE: read the BOOTSTRAP.md file for more information
    - remoteRef:
        key: cloud-github-app-argocd
        property: installation_id
      secretKey: githubAppInstallationID # NOTE: read the BOOTSTRAP.md file for more information
    - remoteRef:
        key: cloud-github-app-argocd
        property: private_key
      secretKey: githubAppPrivateKey # NOTE: read the BOOTSTRAP.md file for more information
  secretStoreRef:
    kind: ClusterSecretStore
    name: kubevault
  target:
    name: argocd-repo-creds-github.chezmoi-sh
    template:
      type: Opaque
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd
          argocd.argoproj.io/secret-type: repo-creds
      data:
        url: https://github.com/chezmoidotsh
        githubAppID: "{{ .githubAppID }}"
        githubAppInstallationID: "{{ .githubAppInstallationID }}"
        githubAppPrivateKey: "{{ .githubAppPrivateKey }}"
