# AWS User for Authelia
#
# Description:
#   These resources will create an AWS IAM User with the necessary permissions
#   to send emails from the domain chezmoi.sh.
---
apiVersion: iam.aws.upbound.io/v1beta1
kind: Policy
metadata:
  annotations:
    crossplane.io/external-name: AutheliaSESSender
  name: nr.chezmoi.sh-amazonses-authelia
spec:
  forProvider:
    path: /nr.chezmoi.sh/
    policy: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Sid": "AllowSendingEmails",
            "Effect": "Allow",
            "Action": [
              "ses:SendEmail",
              "ses:SendRawEmail"
            ],
            "Resource": "arn:aws:ses:eu-west-3:*:identity/chezmoi.sh"
          }
        ]
      }
---
apiVersion: iam.aws.upbound.io/v1beta1
kind: User
metadata:
  annotations:
    crossplane.io/external-name: authelia
  name: nr.chezmoi.sh-amazonses-authelia
spec:
  forProvider:
    path: /nr.chezmoi.sh/
---
apiVersion: iam.aws.upbound.io/v1beta1
kind: UserPolicyAttachment
metadata:
  name: nr.chezmoi.sh-amazonses-authelia
spec:
  forProvider:
    policyArnRef:
      name: nr.chezmoi.sh-amazonses-authelia
    userRef:
      name: nr.chezmoi.sh-amazonses-authelia
---
apiVersion: iam.aws.upbound.io/v1beta1
kind: AccessKey
metadata:
  name: nr.chezmoi.sh-amazonses-authelia
spec:
  forProvider:
    userRef:
      name: nr.chezmoi.sh-amazonses-authelia
