# trunk-ignore-all(checkov/CKV_SECRET_6): no secrets in this file
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: crossplane-nrchezmoish

resources:
  - namespace.yaml
  - aws.iam.authelia.yaml

patches:
  - patch: |-
      apiVersion: iam.aws.upbound.io/v1beta1
      kind: AccessKey
      metadata:
        name: chezmoi.sh-amazonses-authelia
      spec:
        writeConnectionSecretToRef:
          name: security-sso-authelia-aws-ses
          namespace: kubevault-kvstore
